{{ config( 
    alias='g_all_credits', 
    database='agt_comm', 
    schema='contest', 
    materialized = "view" ) }}

WITH LIFE_AND_SEG AS (
    SELECT
        COALESCE(LIFE.UD2, SEG.UD2) AS UD2,
        COALESCE(LIFE.AGENTCODE, SEG.AGENTCODE) AS AGENTCODE,
        SUM(LIFE.FYC_AMOUNT) AS FYC_AMOUNT,
        SUM(LIFE.FYC_CREDITS) AS FYC_CREDITS,
        SUM(SEG.SEG_SALES_AMOUNT) AS SEG_SALES_AMOUNT,
        SUM(SEG.SEG_SALES_CREDIT) AS SEG_SALES_CREDIT,
    FROM
        {{ ref('b_life_credits_agt_comm_contest') }} LIFE FULL
        OUTER JOIN {{ ref('c_segfund_credits_agt_comm_contest') }} SEG ON LIFE.UD2 = SEG.UD2
        AND LIFE.AGENTCODE = SEG.AGENTCODE
    GROUP BY
        1, 2
),
AUM_AND_LIFE_AND_SEG AS (
    SELECT
        COALESCE(AUM.UD2, LIFE_AND_SEG.UD2) AS UD2,
        SUM(FYC_AMOUNT) AS FYC_AMOUNT,
        SUM(FYC_CREDITS) AS FYC_CREDITS,
        MIN(SEG_SALES_AMOUNT) AS SEG_SALES_AMOUNT,
        MIN(SEG_SALES_CREDIT) AS SEG_SALES_CREDIT,
        SUM(SEG_AUMAMOUNT) AS SEG_AUMAMOUNT,
        SUM(SEG_AUMCREDIT) AS SEG_AUMCREDIT
    FROM
        {{ ref('d_aum_credits_agt_comm_contest') }} AUM FULL
        OUTER JOIN LIFE_AND_SEG ON AUM.UD2 = LIFE_AND_SEG.UD2
        AND AUM.AGENTCODE = LIFE_AND_SEG.AGENTCODE
    WHERE
        NOT (
            FYC_CREDITS IS NULL
            AND SEG_SALES_CREDIT IS NULL
            AND SEG_AUMCREDIT = 0
        )
    GROUP BY
        1 
),
MF_AUM_AND_AUM_AND_LIFE_AND_SEG AS (
    SELECT
        COALESCE(AUM_AND_LIFE_AND_SEG.UD2, MF_AUM.UD_2) AS UD2,
        FYC_AMOUNT,
        FYC_CREDITS,
        SEG_SALES_AMOUNT,
        SEG_SALES_CREDIT,
        SEG_AUMAMOUNT,
        SEG_AUMCREDIT,
        MF_AUM.MF_AUMAMOUNT,
        MF_AUM.MF_AUMCREDITS
    FROM
        {{ ref('e_mf_aum_credits_agt_comm_contest') }} MF_AUM FULL
        OUTER JOIN AUM_AND_LIFE_AND_SEG ON AUM_AND_LIFE_AND_SEG.UD2 = MF_AUM.UD_2
),
MF_SALES_AND_MF_AUM_AND_AUM_AND_LIFE_AND_SEG AS (
    SELECT
        COALESCE(X.UD2, SALE.UD_2) AS UD2,
        ZEROIFNULL(FYC_AMOUNT) AS FYC_AMOUNT,
        ZEROIFNULL(FYC_CREDITS) AS FYC_CREDITS,
        ZEROIFNULL(SEG_SALES_AMOUNT) AS SEG_SALES_AMOUNT,
        ZEROIFNULL(SEG_SALES_CREDIT) AS SEG_SALES_CREDIT,
        ZEROIFNULL(SEG_AUMAMOUNT) AS SEGAUMAMOUNT,
        ZEROIFNULL(SEG_AUMCREDIT) AS SEGAUMCREDIT,
        ZEROIFNULL(MF_AUMAMOUNT) AS MF_AUMAMOUNT,
        ZEROIFNULL(MF_AUMCREDITS) AS MF_AUMCREDITS,
        ZEROIFNULL(MF_SALES) AS MF_SALES,
        ZEROIFNULL(MF_SALES_CREDITS) AS MF_SALES_CREDITS
    FROM
        MF_AUM_AND_AUM_AND_LIFE_AND_SEG X FULL
        OUTER JOIN {{ ref('f_mf_sales_credits_agt_comm_contest') }} SALE ON X.UD2 = SALE.UD_2
)
SELECT
    UD2,
    SUM(FYC_AMOUNT) AS FYC_AMOUNT,
    SUM(FYC_CREDITS) AS FYC_CREDITS,
    SUM(SEG_SALES_AMOUNT) AS SEG_SALES_AMOUNT,
    SUM(SEG_SALES_CREDIT) AS SEG_SALES_CREDIT,
    SUM(SEGAUMAMOUNT) AS SEGAUMAMOUNT,
    SUM(SEGAUMCREDIT) AS SEGAUMCREDIT,
    SUM(MF_AUMAMOUNT) AS MF_AUMAMOUNT,
    SUM(MF_AUMCREDITS) AS MF_AUMCREDITS,
    SUM(MF_SALES) AS MF_SALES,
    SUM(MF_SALES_CREDITS) AS MF_SALES_CREDITS,
    SUM(
        FYC_AMOUNT + SEG_SALES_AMOUNT + SEGAUMAMOUNT + MF_AUMAMOUNT + MF_SALES
    ) AS AmountTOT,
    SUM(
        FYC_CREDITS + SEG_SALES_CREDIT + SEGAUMCREDIT + MF_AUMCREDITS + MF_SALES_CREDITS
    ) AS TOTCredits
FROM
    MF_SALES_AND_MF_AUM_AND_AUM_AND_LIFE_AND_SEG
WHERE
    UD2 is not null
    and contains(UD2, '/') = false
    and contains(UD2, '-') = false
GROUP BY
    1   