{{			
    config (			
        materialized="view",			
        alias='broker_fh', 			
        database='report', 			
        schema='daily_apps',
        tags=["daily_apps"]			
    )			
}}	

SELECT
    PARENTNODEID,
    AGENTCODE,
    FIRSTNAME,
    MIDDLENAME,
    LASTNAME,
    AGENTNAME,
    CL_ADVISOR_GROUP_IDENTIFIER,
    COMPANYNAME,
    MGACODE,
    AGACODE,
    DATEOFBIRTH,
    PROVINCE,
    COMPANYPROVINCE,
    AGENTSTATUS,
    AGENTTYPE,
    LANGUAGEPREFERENCE,
    SERVICELEVEL,
    CREATEDDATE,
    BROKERID,
    LASTMODIFIEDDATE,
    USERDEFINED2,
    EMAIL,
    CASLAPPROVED,
    SEGMENTA,
    SEGMENTB,
    SEGMENTC,
    SEGMENTTAGWS,
    AAP_TAG,
    ADSL_TAG,
    ELEVATED,
    PENDINGTERMINATION,
    TERMINATED,
    TRANSFERRINGOUT,
    COS_SALES_BDC,
    COS_SALES_BDD,
    COS_SALES_RVP
FROM
    {{ ref('broker_fh_cl_integrate_insurance') }}
GROUP BY ALL
