
version: 2

sources:
  - name: insurance_curated
    database: fh_prod
    schema: wealthserv_ins_curated_secure
    tables:
      - name: hierarchy_vc
      - name: broker_vc
      - name: brokeradvanced_vc
      - name: brokeraddress_vc
      - name: brokerphone_vc
      - name: brokeremail_vc
      - name: brokertags_vc
      - name: representatives_vc
      - name: representativeaddress_vc
  
  - name: investment_curated
    database: fh_prod
    schema: wealthserv_inv_curated_secure
    tables:
      - name: representatives_vc
      - name: representativeaddress_vc

  - name: insurance
    database: fh_prod
    schema: wealthserv_ins_ods_current_secure
    tables:
      - name: clients
      - name: state
      - name: constants
      - name: ic
      - name: agent
      - name: icplan
      - name: policy
      - name: policygroup
      - name: policygrouplinking
      - name: policysplit
      - name: aga
      - name: mga
      - name: tags
      - name: policystatus
      - name: hierarchytags
      - name: indirecthierarchyrelationship
      - name: brokertags
      - name: clienttags
      - name: clientagentlinking
      - name: policytags
      - name: policyclientlinking
      - name: policyagentlinking
      - name: accruals
      - name: importednbpolicy
      - name: agent_combined_integrate_insurance

  - name: investment
    database: fh_prod
    schema: wealthserv_inv_ods_current_secure
    tables:
      - name: clients
      - name: sponsor
      - name: fund_products
      - name: producttypes
      - name: state
      - name: registration
      - name: trailing_fee
      - name: fundaccount
      - name: transactiontypes
      - name: paycommission
      - name: representatives
      - name: branch
      - name: transactions
      - name: region
      - name: dealer   
      - name: constants
      - name: beneficiaries
      - name: accountholder
      