
version: 2

sources:
  - name: insurance_curated
    database: fh_prod
    schema: wealthserv_ins_curated_secure
    tables:
      - name: hierarchy_vc
      - name: recursivehierarchy_vc
      - name: broker_vc
      - name: brokeradvanced_vc
      - name: brokeraddress_vc
      - name: brokercarrierdebt_vc
      - name: brokercontractprovince_vc
      - name: brokercontractstatus_vc
      - name: brokercontracttype_vc
      - name: brokercontract_vc
      - name: brokercos_vc
      - name: brokerphone_vc
      - name: brokeremail_vc
      - name: brokertags_vc
      - name: brokerledgersummary_vc 
      - name: commission_vc
      - name: commissiongrid_vc
      - name: representatives_vc
      - name: representativeaddress_vc
      - name: policy_vc
      - name: policystatus_vc
      - name: policytags_vc
      - name: cosrole_vc
      - name: employee_vc
      - name: employeerole_vc
      - name: ic_vc
  
  - name: investment_curated
    database: fh_prod
    schema: wealthserv_inv_curated_secure
    tables:
      - name: aua_vc
      - name: branches_vc
      - name: fundaccount_vc
      - name: fundproducts_vc
      - name: jointrepresentatives_vc
      - name: region_vc
      - name: representatives_vc
      - name: representativeaddress_vc
      - name: sponsors_vc
      - name: transactions_vc
      - name: transactiontypes_vc
      
  - name: insurance
    database: fh_prod
    schema: wealthserv_ins_ods_current_secure
    tables:
      - name: cheque
      - name: clients
      - name: commissionrun
      - name: commissiontrx
      - name: state
      - name: constants
      - name: ic
      - name: icagent
      - name: agent
      - name: icplan
      - name: policy
      - name: policyagentlinking
      - name: policygroup
      - name: policygrouplinking
      - name: policysplit
      - name: policystatuschanges
      - name: aga
      - name: mga
      - name: tags
      - name: policystatus
      - name: hierarchytags
      - name: indirecthierarchyrelationship
      - name: brokertags
      - name: clienttags
      - name: clientagentlinking
      - name: policytags
      - name: policyclientlinking
      - name: accruals
      - name: importednbpolicy
      - name: agent_combined_integrate_insurance

  - name: investment
    database: fh_prod
    schema: wealthserv_inv_ods_current_secure
    tables:
      - name: clients
      - name: cheque
      - name: sponsor
      - name: fund_products
      - name: producttypes
      - name: state
      - name: registration
      - name: trailing_fee
      - name: fundaccount
      - name: transactiontypes
      - name: transactionstatus
      - name: paycommission
      - name: representatives
      - name: branch
      - name: transactions
      - name: region
      - name: dealer   
      - name: constants
      - name: beneficiaries
      - name: accountholder
      
  - name: investment_raw
    database: fh_prod
    schema: wealthserv_inv_ods_raw_secure
    tables:
      - name: transactions

  - name: dimensions
    database: integrate
    schema: prod_dimensions
    tables:
      - name: month_name
      - name: calendar
      - name: plancategory_map
      - name: agent_firm_segment_map
      
  - name: app_tables
    database: applications
    schema: prod_loi
    tables:
      - name: loi_tracking

  - name: contest
    database: agt_comm
    schema: prod_contest
    tables:
      - name: date_ranges
      - name: total_contest_credits
      - name: total_contest_production
      - name: contract_dt_adjustment
      - name: canada_life
     
  - name: integrate
    schema: prod_insurance
    tables:
      - name: policy_fh_cl
      - name: hierarchy_fh_cl
