
version: 2

sources:
  - name: insurance_curated
    database: fh_prod
    schema: wealthserv_ins_curated_secure
    tables:
      - name: assistant_vc
      - name: assistantaddress_vc
      - name: assistantemail_vc
      - name: broker_vc
      - name: brokeradvanced_vc
      - name: brokeraddress_vc
      - name: brokerassistant_vc
      - name: brokercarrierdebt_vc
      - name: brokercontractprovince_vc
      - name: brokercontractstatus_vc
      - name: brokercontracttype_vc
      - name: brokercontract_vc
      - name: brokercos_vc
      - name: brokereo_vc
      - name: brokeremail_vc
      - name: brokergroupcategory_vc
      - name: brokergroupmembership_vc
      - name: brokergroup_vc
      - name: brokerledgersummary_vc
      - name: brokermarketingoffice_vc
      - name: brokerphone_vc
      - name: brokerreplink_vc
      - name: brokertags_vc 
      - name: brokertasks_vc
      - name: carrierplan_vc
      - name: cascadedbrokertags_vc
      - name: cascadedclienttags_vc
      - name: cascadedhierearchytags_vc
      - name: cascadedpolicytags_vc
      - name: clientstatus_vc
      - name: clienttype_vc
      - name: client_vc
      - name: commission_vc
      - name: commissiongrid_vc
      - name: commissiongriddetails_vc
      - name: cosrole_vc
      - name: employee_vc
      - name: employeerole_vc
      - name: employers_vc
      - name: entitytags_vc
      - name: hierarchycontract_vc
      - name: hierarchyeo_vc
      - name: hierarchy_vc
      - name: ic_vc
      - name: insuranceuser_vc
      - name: marketingoffice_vc
      - name: mga_vc
      - name: planmodalfactor_vc
      - name: policybridge_vc
      - name: policycos_vc
      - name: policyrider_vc
      - name: policytasks_vc
      - name: policy_vc
      - name: policystatus_vc
      - name: policytags_vc
      - name: rider_vc
      - name: taskpriority_vc
      - name: taskstatus_vc
      - name: tasks_vc
      - name: tasktype_vc
      - name: usergroup_vc
  
  - name: investment_curated
    database: fh_prod
    schema: wealthserv_inv_curated_secure
    tables:
      - name: aua_vc
      - name: branches_vc
      - name: dealer_vc
      - name: fundaccount_vc
      - name: fundproducts_vc
      - name: jointrepresentatives_vc
      - name: processedcommissions_vc
      - name: processedtrailfees_vc
      - name: purchases_vc
      - name: region_vc
      - name: representatives_vc
      - name: representativeaddress_vc
      - name: representativeemail_vc
      - name: sponsors_vc
      - name: trailingfees_vc
      - name: transactions_vc
      - name: transactiontypes_vc
      - name: users_vc
      
  - name: insurance
    database: fh_prod
    schema: wealthserv_ins_ods_current_secure
    tables:
      - name: cheque
      - name: clients
      - name: commissionrun
      - name: commissiontrx
      - name: state
      - name: constants
      - name: ic
      - name: icagent
      - name: agent
      - name: icplan
      - name: policy
      - name: policyagentlinking
      - name: policygroup
      - name: policygrouplinking
      - name: policysplit
      - name: policystatuschanges
      - name: aga
      - name: mga
      - name: tags
      - name: policystatus
      - name: hierarchytags
      - name: indirecthierarchyrelationship
      - name: brokertags
      - name: clienttags
      - name: clientagentlinking
      - name: policytags
      - name: policyclientlinking
      - name: accruals
      - name: importednbpolicy
      - name: agent_combined_integrate_insurance

  - name: investment
    database: fh_prod
    schema: wealthserv_inv_ods_current_secure
    tables:
      - name: clients
      - name: cheque
      - name: sponsor
      - name: fund_products
      - name: producttypes
      - name: state
      - name: registration
      - name: trailing_fee
      - name: fundaccount
      - name: transactiontypes
      - name: transactionstatus
      - name: paycommission
      - name: representatives
      - name: branch
      - name: transactions
      - name: region
      - name: dealer   
      - name: constants
      - name: beneficiaries
      - name: accountholder
      
  - name: investment_raw
    database: fh_prod
    schema: wealthserv_inv_ods_raw_secure
    tables:
      - name: transactions

  - name: dimensions
    database: integrate
    schema: prod_dimensions
    tables:
      - name: month_name
      - name: calendar
      - name: plancategory_map
      - name: agent_firm_segment_map
      
  - name: app_tables
    database: applications
    schema: prod_loi
    tables:
      - name: loi_tracking
      - name: fundserv_daily_metrics
      - name: ws_inv_cleanup_monthly

  - name: fs_app_tables
    database: applications
    schema: fundserv_data
    tables:
      - name: fundserv_daily_metrics
      - name: ws_inv_cleanup_monthly

  - name: contest
    database: agt_comm
    schema: prod_contest
    tables:
      - name: date_ranges
      - name: total_contest_credits
      - name: total_contest_production
      - name: contract_dt_adjustment
      - name: canada_life

  - name: acdirect
    database: integrate
    schema: prod_insurance
    tables:
      - name: daily_insurance_acdirect
      - name: daily_insurance_ac_direct_agreement
     

  - name: acdirect_broker
    database: integrate
    schema: prod_insurance
    tables:
      - name: ac_direct_advisor_info
      - name: acdirect_advisor_info
      - name: acdirect_info_current

  - name: ac_direct_current
    database: report_cl
    schema: dev_la
    tables:
      - name: acdirect_info_current

  - name: budget_2025
    database: report
    schema: prod_daily_apps
    tables:
      - name: budget_2025

  - name: acdirect_sandbox
    database: sandbox
    schema: leo
    tables:
      - name: daily_insurance_acdirect
      - name: daily_insurance_ac_direct_agreement

  - name: rls_users
    database: report
    schema: prod_rls
    tables:
      - name: users

  - name: ren_comm
    database: clean_comm
    schema: extracts
    tables:
      - name: bmo
      - name: canadalife
      - name: manulife
      - name: sli
      - name: rbc
      - name: equitable

  - name: finance
    database: finance
    schema: archive
    tables:
      - name: advisors
      - name: aum
      - name: aummfd
      - name: infovr
      - name: insurance
      - name: mfd
      - name: ncfmfd
      - name: ncfmga
      - name: rbc


     

  