{{			
    config (			
        materialized="view",			
        alias='policy_fh', 			
        database='report', 			
        schema = 'in_the_mill',
        grants = {'ownership': ['FH_READER']},
        tags=["in_the_mill", "large_case"]			
    )			
}}

    SELECT
        POL.FH_POLICYCATEGORY,
        POLICYCODE,
        FH_SERVICINGAGTCODE,
        FH_SERVICINGAGTSPLIT,
        FH_COMMISSIONINGAGTCODE,
        FH_COMMISSIONINGAGTSPLIT,
        FH_CARRIERENG,
        FH_CARRIERFR,
        POL.POLICYNUMBER,
        PLANID,
        FH_PLANTYPE,
        FH_PLANNAMEENG,
        FH_PLANNAMEFR,
        PREMIUMAMOUNT,
        CREATEDDATE,
        FH_STATUSCODE,
        FH_STATUSNAMEENG,
        FH_STATUSNAMEFR,
        FH_STATUSCATEGORY,
        APPCOUNT,
        FH_FYCSERVAMT,
        FH_FYCCOMMAMT,
        ISSUEPROVINCE,
        FH_APPSOURCE,
        FH_APPTYPE,
        POL.FH_SETTLEMENTDATE,
        POL.FH_STARTDATE,
        FH_PREMIUM,
        FH_PREM_COMMWGT,
        FH_PREM_SERVWGT,
        POL.FH_PLACEDDATE,
        FH_FYCPLACED,
        FH_ITM_END_DATE,
        FH_ITM,
        FH_DAYS_IN_STATUS,
    CASE
        WHEN WRIT.POLICYGROUPCODE IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS WRITTEN_LG_CASE,
    CASE
        WHEN WRIT.POLICYGROUPCODE IS NULL THEN TRUE
        ELSE FALSE
    END AS WRITTEN_NORMAL_CASE,
    CASE
        WHEN WRIT_NORM.POLICYGROUPCODE IS NOT NULL THEN WRIT_NORM.WRITTEN_COMM_PREM 
    END AS WRITTEN_NORMAL_CASE_PREM,
    CASE
        WHEN WRIT.POLICYGROUPCODE IS NOT NULL THEN WRIT.WRITTEN_COMM_PREM  
    END AS WRITTEN_LARGE_CASE_PREM,
    CASE
        WHEN PD.POLICYGROUPCODE IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS PAID_LG_CASE,
    CASE
        WHEN PD_NORM.POLICYGROUPCODE IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS PAID_NORMAL_CASE,
    CASE
        WHEN PD.POLICYGROUPCODE IS NOT NULL THEN PD.PAID_COMM_PREM 
    END AS PAID_LARGE_CASE_PREM,
    CASE
        WHEN PD_NORM.POLICYGROUPCODE IS NOT NULL THEN PD_NORM.PAID_COMM_PREM 
    END AS PAID_NORMAL_CASE_PREM,
     CASE
        WHEN PLACE.POLICYGROUPCODE IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS PLACED_LG_CASE,
    CASE
        WHEN PLACE_NORM.POLICYGROUPCODE IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS PLACED_NORMAL_CASE,
    CASE
        WHEN PLACE.POLICYGROUPCODE IS NOT NULL THEN PLACE.PLACED_COMM_PREM
    END AS PLACED_LARGE_CASE_PREM,
    CASE
        WHEN PLACE_NORM.POLICYGROUPCODE IS NOT NULL THEN PLACE_NORM.PLACED_COMM_PREM
    END AS PLACED_NORMAL_CASE_PREM,
    CASE
        WHEN FH_SETTLEMENTDATE is not null THEN 'Paid Status'
        WHEN FH_STATUSCODE = 'ADLR' THEN 'Placed but not yet Paid'
        WHEN FH_STATUSCODE = 'APND' THEN 'Pending UW'
        WHEN FH_STATUSCODE = 'AISS' THEN 'Approved'
        WHEN FH_STATUSCODE = 'AISD' THEN 'Issued'
        ELSE 'Terminated'
    END AS FUNNEL_TAG
    FROM
        {{ ref('policy_itm_fh_insurance_report') }} POL
    LEFT JOIN {{ ref('written_large_case_report_in_the_mill') }} WRIT ON POL.POLICYGROUPCODE = WRIT.POLICYGROUPCODE
    AND POL.FH_STARTDATE = WRIT.FH_STARTDATE
    LEFT JOIN {{ ref('paid_large_case_report_in_the_mill') }} PD ON POL.POLICYGROUPCODE = PD.POLICYGROUPCODE
    AND POL.FH_POLICYCATEGORY = PD.FH_POLICYCATEGORY
    LEFT JOIN {{ ref('written_normal_case_report_in_the_mill') }} WRIT_NORM ON POL.POLICYGROUPCODE = WRIT_NORM.POLICYGROUPCODE
    AND POL.FH_STARTDATE = WRIT_NORM.FH_STARTDATE
    LEFT JOIN {{ ref('paid_normal_case_report_in_the_mill') }} PD_NORM ON POL.POLICYGROUPCODE = PD_NORM.POLICYGROUPCODE
    AND POL.FH_POLICYCATEGORY = PD_NORM.FH_POLICYCATEGORY
    LEFT JOIN {{ ref('placed_large_case_report_in_the_mill') }} PLACE ON  POL.POLICYGROUPCODE = PLACE.POLICYGROUPCODE 
    AND POL.FH_POLICYCATEGORY = PLACE.FH_POLICYCATEGORY
    LEFT JOIN {{ ref('placed_normal_case_report_in_the_mill') }} PLACE_NORM ON POL.POLICYGROUPCODE = PLACE_NORM.POLICYGROUPCODE
    AND POL.FH_POLICYCATEGORY = PLACE_NORM.FH_POLICYCATEGORY
 