{{  
    config(alias='segfund_report_transactions_fh', 
    database='normalize', 
    schema='investment')  
}} 

SELECT
    CODE AS TRANSACTIONCODE,
    FUNDACCOUNT_CODE AS FUNDACCOUNT_CODE,
    SOURCE_NUMBER AS SOURCE_NUMBER,
    REP_CODE AS TRANSACTIONREPCODE,
    NULL AS CLIENTREPCODE,
    SETLEMENT_DATE AS SETTLEMENTDATE,
    TRADE_DATE AS TRADEDATE,
    SHARES_UNITS AS SHARES_UNITS,
    UNIT_PRICE AS UNIT_PRICE,
    AMOUNT * TT.DBSIGN AS AMOUNT,
    SETTLEMENTAMOUNT * TT.DBSIGN AS NETAMOUNT,
    DEALER_COMMISSION AS GROSSCOMMISSION,
    DEPOSIT_DATE AS DEPOSIT_DATE,
    CURRENCYNAME AS CURRENCYNAME,
    PAYMENT_STATUS AS PAYMENTSTATUS,
    T.EXT_TYPE_CODE AS TRANSACTIONTYPECODE,
    FUNDPRODUCT_CODE AS FUNDPRODUCTCODE,
    MANUALENTRYFLAG AS MANUALENTRYFLAG,
    ENTEREDBY AS ENTEREDBYUSERID,
    COMM_DATA.INVESTMENT_AMOUNT,
    COMM_DATA.COMMISSION_CHEQUE_DATE,
    NULL AS SF_PROD_TRANSACTION_DATE,
    COMM_DATA.COMMISSION_CHEQUE_DATE AS SEGFUND_REPORT_DATE
FROM
    {{ ref('__base_transactions_remove_splitcode_normalize_investment') }} T
    JOIN {{ ref('transactiontypes_fh_normalize_investment') }} TT ON T.EXT_TYPE_CODE = TT.TRANSACTIONTYPECODE
    JOIN {{ ref('commissionable_data_summary_extract_transaction_normalize_investment') }} COMM_DATA ON T.CODE = COMM_DATA.TRANSACTION_CODE
WHERE
    COMM_DATA.GROSS_COMMISSION != 0
GROUP BY
    ALL
UNION
SELECT
    CODE AS TRANSACTIONCODE,
    FUNDACCOUNT_CODE AS FUNDACCOUNT_CODE,
    SOURCE_NUMBER AS SOURCE_NUMBER,
    REP_CODE AS TRANSACTIONREPCODE,
    NULL AS CLIENTREPCODE,
    SETLEMENT_DATE AS SETTLEMENTDATE,
    TRADE_DATE AS TRADEDATE,
    SHARES_UNITS AS SHARES_UNITS,
    UNIT_PRICE AS UNIT_PRICE,
    AMOUNT AS AMOUNT,
    SETTLEMENTAMOUNT AS NETAMOUNT,
    DEALER_COMMISSION AS GROSSCOMMISSION,
    DEPOSIT_DATE AS DEPOSIT_DATE,
    CURRENCYNAME AS CURRENCYNAME,
    PAYMENT_STATUS AS PAYMENTSTATUS,
    EXT_TYPE_CODE AS TRANSACTIONTYPECODE,
    FUNDPRODUCT_CODE AS FUNDPRODUCTCODE,
    MANUALENTRYFLAG AS MANUALENTRYFLAG,
    ENTEREDBY AS ENTEREDBYUSERID,
    NULL AS COMM_DATA_INVESTMENT_AMOUNT,
    NULL AS COMMISSION_CHEQUE_DATE,
    SF_PROD.TRANSACTION_DATE,
    SF_PROD.TRANSACTION_DATE AS SEGFUND_REPORT_DATE
FROM
    {{ ref('__base_transactions_remove_splitcode_normalize_investment') }} T
    JOIN {{ ref('segfund_production_report_transaction_normalize_investment') }} SF_PROD ON T.CODE = SF_PROD.TRANSACTION_ID
GROUP BY
    ALL