 {{  config(alias='sponsor_consultant', database='normalize', schema='investment')  }} 


SELECT
 accountbalance as investment_fund_sponsor_accountbalance
,accountbalance1 as investment_fund_sponsor_accountbalance1
,accountbalance1_startcheque as investment_fund_sponsor_accountbalance1_startcheque
,accountbalance1_startcheque2 as investment_fund_sponsor_accountbalance1_startcheque2
,accountbalance_date as investment_fund_sponsor_accountbalance_date
,accountbalance_startcheque as investment_fund_sponsor_accountbalance_startcheque
,accountbalance_startcheque2 as investment_fund_sponsor_accountbalance_startcheque2
,address as investment_fund_sponsor_address
,address2 as investment_fund_sponsor_address2
,alias as investment_fund_sponsor_alias
,annuity_flag as investment_fund_sponsor_annuity_flag
,bankaccount as investment_fund_sponsor_bankaccount
,bankaccount1 as investment_fund_sponsor_bankaccount1
,bankbranch as investment_fund_sponsor_bankbranch
,bankbranch1 as investment_fund_sponsor_bankbranch1
,bankcode as investment_fund_sponsor_bankcode
,bankcode1 as investment_fund_sponsor_bankcode1
,bankname as investment_fund_sponsor_bankname
,bankname1 as investment_fund_sponsor_bankname1
,banktransit as investment_fund_sponsor_banktransit
,banktransit1 as investment_fund_sponsor_banktransit1
,bd_number as investment_fund_sponsor_bd_number
,bond_flag as investment_fund_sponsor_bond_flag
,cash_flag as investment_fund_sponsor_cash_flag
,ccy as investment_fund_sponsor_ccy
,ccy1 as investment_fund_sponsor_ccy1
,cdc_operation as investment_fund_sponsor_cdc_operation
,cd_flag as investment_fund_sponsor_cd_flag
,changedby as investment_fund_sponsor_changedby
,changedon as investment_fund_sponsor_changedon
,city as investment_fund_sponsor_city
,code as investment_fund_sponsor_code
,commit_timestamp as investment_fund_sponsor_commit_timestamp
,cpsid as investment_fund_sponsor_cpsid
,css_flag as investment_fund_sponsor_css_flag
,datalake_end_ts as investment_fund_sponsor_datalake_end_ts
,datalake_start_ts as investment_fund_sponsor_datalake_start_ts
,datalake_timestamp as investment_fund_sponsor_datalake_timestamp
,dbx_old_print_cheq as investment_fund_sponsor_dbx_old_print_cheq
,dbx_old_sponsor as investment_fund_sponsor_dbx_old_sponsor
,dpp_flag as investment_fund_sponsor_dpp_flag
,eo_flag as investment_fund_sponsor_eo_flag
,french_name as investment_fund_sponsor_french_name
,fundserv_flag as investment_fund_sponsor_fundserv_flag
,import_source as investment_fund_sponsor_import_source
,insurance_flag as investment_fund_sponsor_insurance_flag
,interestpaid as investment_fund_sponsor_interestpaid
,invest_flag as investment_fund_sponsor_invest_flag
,is_first_known_record as investment_fund_sponsor_is_first_known_record
,is_last_known_record as investment_fund_sponsor_is_last_known_record
,market_business_phone as investment_fund_sponsor_market_business_phone
,market_cell_phone as investment_fund_sponsor_market_cell_phone
,market_contact as investment_fund_sponsor_market_contact
,market_email_address as investment_fund_sponsor_market_email_address
,market_fax as investment_fund_sponsor_market_fax
,market_phone_ext as investment_fund_sponsor_market_phone_ext
,mutualfund_flag as investment_fund_sponsor_mutualfund_flag
,name as investment_fund_sponsor_name
,netdirect_flag as investment_fund_sponsor_netdirect_flag
,netsettlebalance as investment_fund_sponsor_netsettlebalance
,netsettlebalance1 as investment_fund_sponsor_netsettlebalance1
,note as investment_fund_sponsor_note
,noteflag as investment_fund_sponsor_noteflag
,note_flag as investment_fund_sponsor_note_flag
,oper_business_phone as investment_fund_sponsor_oper_business_phone
,oper_cell_phone as investment_fund_sponsor_oper_cell_phone
,oper_contact as investment_fund_sponsor_oper_contact
,oper_email_address as investment_fund_sponsor_oper_email_address
,oper_fax as investment_fund_sponsor_oper_fax
,oper_phone_ext as investment_fund_sponsor_oper_phone_ext
,option_flag as investment_fund_sponsor_option_flag
,others_flag as investment_fund_sponsor_others_flag
,parentcode as investment_fund_sponsor_parentcode
,payment_type as investment_fund_sponsor_payment_type
,preferred_flag as investment_fund_sponsor_preferred_flag
,private_flag as investment_fund_sponsor_private_flag
,recycle_flag as investment_fund_sponsor_recycle_flag
,referral_flag as investment_fund_sponsor_referral_flag
,resend_flag as investment_fund_sponsor_resend_flag
,sponsorid as investment_fund_sponsor_sponsorid
,sponsortype as investment_fund_sponsor_sponsortype
,stage_id as investment_fund_sponsor_stage_id
,state_code as investment_fund_sponsor_state_code
,status as investment_fund_sponsor_status
,stock_flag as investment_fund_sponsor_stock_flag
,stream_position as investment_fund_sponsor_stream_position
,transact_id as investment_fund_sponsor_transact_id
,userdefined_data1 as investment_fund_sponsor_userdefined_data1
,userdefined_data2 as investment_fund_sponsor_userdefined_data2
,web as investment_fund_sponsor_web
,wsnetworkcode as investment_fund_sponsor_wsnetworkcode
,ytdallinvestedamount as investment_fund_sponsor_ytdallinvestedamount
,ytdgrosscommission as investment_fund_sponsor_ytdgrosscommission
,ytdinvestedamount as investment_fund_sponsor_ytdinvestedamount
,ytdpayout as investment_fund_sponsor_ytdpayout
,ytdpayout1 as investment_fund_sponsor_ytdpayout1
,zip_code as investment_fund_sponsor_zip_code
,_infx_loaded_ts_utc 
,_infx_active_from_ts_utc 
,_infx_active_to_ts_utc  
,_infx_is_active 


from {{ ref ('sponsor_clean_investment')  }}