 {{  config(alias='transactiontypes', database='normalize', schema='investment')  }} 


SELECT 
 annuity_flag as investment_transactiontypes_annuity_flag
,autoswitch_flag as investment_transactiontypes_autoswitch_flag
,bond_flag as investment_transactiontypes_bond_flag
,book_flag as investment_transactiontypes_book_flag
,category_flag as investment_transactiontypes_category_flag
,cdc_operation as investment_transactiontypes_cdc_operation
,cd_flag as investment_transactiontypes_cd_flag
,changedby as investment_transactiontypes_changedby
,changedon as investment_transactiontypes_changedon
,clientrorflag as investment_transactiontypes_clientrorflag
,commissionrun_flag as investment_transactiontypes_commissionrun_flag
,commission_flag as investment_transactiontypes_commission_flag
,commit_timestamp as investment_transactiontypes_commit_timestamp
,datalake_end_ts as investment_transactiontypes_datalake_end_ts
,datalake_start_ts as investment_transactiontypes_datalake_start_ts
,datalake_timestamp as investment_transactiontypes_datalake_timestamp
,dbsign as investment_transactiontypes_dbsign
,defaultrorflag as investment_transactiontypes_defaultrorflag
,displaying_index as investment_transactiontypes_displaying_index
,display_name as investment_transactiontypes_display_name
,display_namefr as investment_transactiontypes_display_namefr
,dividend_flag as investment_transactiontypes_dividend_flag
,dpp_flag as investment_transactiontypes_dpp_flag
,excludedcommissionimportchecks as investment_transactiontypes_excludedcommissionimportchecks
,excludedtransactionimportchecks as investment_transactiontypes_excludedtransactionimportchecks
,externaltransfer_flag as investment_transactiontypes_externaltransfer_flag
,ext_type_code as investment_transactiontypes_ext_type_code
,ext_type_name as investment_transactiontypes_ext_type_name
,ext_type_namefr as investment_transactiontypes_ext_type_namefr
,insurance_flag as investment_transactiontypes_insurance_flag
,internaltransfer_flag as investment_transactiontypes_internaltransfer_flag
,invest_flag as investment_transactiontypes_invest_flag
,is_first_known_record as investment_transactiontypes_is_first_known_record
,is_last_known_record as investment_transactiontypes_is_last_known_record
,mf_flag as investment_transactiontypes_mf_flag
,note_flag as investment_transactiontypes_note_flag
,nounits_flag as investment_transactiontypes_nounits_flag
,option_flag as investment_transactiontypes_option_flag
,other_flag as investment_transactiontypes_other_flag
,processtype as investment_transactiontypes_processtype
,purchase_flag as investment_transactiontypes_purchase_flag
,quickentrydisplay as investment_transactiontypes_quickentrydisplay
,quickentryflag as investment_transactiontypes_quickentryflag
,redemption_flag as investment_transactiontypes_redemption_flag
,reprightflag as investment_transactiontypes_reprightflag
,ror as investment_transactiontypes_ror
,ror_adjustment_flag as investment_transactiontypes_ror_adjustment_flag
,stage_id as investment_transactiontypes_stage_id
,stock_flag as investment_transactiontypes_stock_flag
,stream_position as investment_transactiontypes_stream_position
,switch_flag as investment_transactiontypes_switch_flag
,systematic_flag as investment_transactiontypes_systematic_flag
,tradeapproval_flag as investment_transactiontypes_tradeapproval_flag
,tradeapproval_minamount as investment_transactiontypes_tradeapproval_minamount
,tradecompliance_flag as investment_transactiontypes_tradecompliance_flag
,tradeextinvest_flag as investment_transactiontypes_tradeextinvest_flag
,tradeexttype_flag as investment_transactiontypes_tradeexttype_flag
,transact_id as investment_transactiontypes_transact_id
,type_flag as investment_transactiontypes_type_flag
,va_flag as investment_transactiontypes_va_flag
,warrant_flag as investment_transactiontypes_warrant_flag
,_infx_loaded_ts_utc 
,_infx_active_from_ts_utc 
,_infx_active_to_ts_utc  
,_infx_is_active 


from {{ ref ('transactiontypes_clean_investment')  }}