 {{			
    config (			
        materialized="view",			
        alias='transactions_fh', 			
        database='normalize', 			
        schema='investment'  		
    )			
}}

WITH SETTLED_NC as (
    SELECT
        *
    FROM
        NORMALIZE.PROD_INVESTMENT.SF_PROD_RPT_TEST
    WHERE
        TRANSACTION_STATUS = 'Settled N/C'
)
SELECT
    T_VC.TRANSACTIONCODE,
    T_VC.FUNDACCOUNT_CODE,
    T_VC.SOURCE_NUMBER,
    T_VC.TRANSACTIONREPCODE,
    T_VC.CLIENTREPCODE,
    T_VC.SETTLEMENTDATE,
    T_VC.TRADEDATE,
    COMM_PD.COMMISSION_CHEQUE_DATE AS COMMISSION_CHEQUE_DATE,
    NO_COMM.TRANSACTION_DATE AS SETT_NO_COMM_DT,
    COALESCE(
        COMMISSION_CHEQUE_DATE,
        SETT_NO_COMM_DT,
        t_vc.TRADEDATE
    ) AS DATE_FOR_SEGFUNDS_REPORT,
    T_VC.SHARES_UNITS,
    T_VC.SHARES_UNITS,
    T_VC.UNIT_PRICE,
    T_VC.AMOUNT,
    T_VC.NETAMOUNT,
    T_VC.GROSSCOMMISSION,
    T_VC.DEPOSIT_DATE,
    T_VC.CURRENCYNAME,
    T_VC.PAYMENTSTATUS,
    T_VC.TRANSACTIONTYPECODE,
    T_VC.FUNDPRODUCTCODE,
    T_VC.MANUALENTRYFLAG,
    T_VC.ENTEREDINSYSTEMFLAG,
    T_VC.ENTEREDBYUSERID,
    T_VC.APPROVALDATE,
    T_VC.APPROVALBY,
    T_VC.SECAPPROVALDATE,
    T_VC.SECAPPROVALBY
FROM
    NORMALIZE.PROD_INVESTMENT.TRANSACTIONS_VC T_VC
    LEFT JOIN NORMALIZE.PROD_INVESTMENT.COMM_DATA_SUMM_TEST COMM_PD on COMM_PD.TRANSACTION_CODE = T_VC.TRANSACTIONCODE
    LEFT JOIN SETTLED_NC NO_COMM on NO_COMM.CODE = T_VC.TRANSACTIONCODE