{{ config(alias='empire', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}} 

SELECT
    'Empire' as "COMPANY",
    CAST("PRODUCER ID" as VARCHAR) as "AGENT SELLING CODE",
    CASE
        WHEN TRIM("POLICY NUMBER") = 'nan' THEN NULL
        ELSE TRIM("POLICY NUMBER")
    END AS "POLICY",  
    CASE
        WHEN TRIM("CVG INSURED LAST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED LAST NAME")
    END AS "LAST NAME",  
    CASE
        WHEN TRIM("CVG INSURED FIRST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED FIRST NAME")
    END AS "FIRST NAME",
    CASE
        WHEN TRIM("POLICY OWNER LAST NAME") = 'nan' THEN NULL
        ELSE TRIM("POLICY OWNER LAST NAME")
    END AS "POLICY OWNER LAST NAME",  
    CASE
        WHEN TRIM("POLICY OWNER FIRST NAME") = 'nan' THEN NULL
        ELSE TRIM("POLICY OWNER FIRST NAME")
    END AS "POLICY OWNER FIRST NAME",    
    "COVERAGE NUMBER",
    DATE("DATE GENERATED") AS "GENERATION DATE",
    "COMM. TYPE", 
    CASE
        WHEN TRIM("PRODUCT NAME") = 'nan' THEN NULL
        ELSE TRIM("PRODUCT NAME")
    END AS "PRODUCT",  
    CASE
        WHEN TRIM(CAST("PRODUCT CODE" AS VARCHAR)) = 'nan' THEN NULL
        ELSE TRIM(CAST("PRODUCT CODE" AS VARCHAR))
    END AS "BASIC PLAN CODE",
    MODE,
    "COMMISSION RATE",
    "COMMISSIONABLE_AMT" as "STATEMENT BASIS AMOUNT",           
    "COMM. AMT" as "AMOUNT",
    "SHARE" as "SHARE %",
     CASE
        WHEN TRIM("CVG INSURED FIRST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED FIRST NAME")
    END AS "BUSINESS FIRST NAME",    
    CASE
        WHEN TRIM("CVG INSURED LAST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED LAST NAME")
    END AS "BUSINESS SURNAME", 
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR")
    END AS "FROM/TO ADVISOR",  
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR SURNAME") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR SURNAME")
    END AS "FROM/TO ADVISOR SURNAME",      
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR NAME") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR NAME")
    END AS "FROM/TO ADVISOR NAME",     
    "ISSUE LOCATION",  
    CASE
        WHEN LEFT("COMM. TYPE", POSITION('-' in "COMM. TYPE") - 1) IN ('FYC', 'FOV') THEN 'First Year'
        WHEN LEFT("COMM. TYPE", POSITION('-' in "COMM. TYPE") - 1) IN ('REN', 'SVF', 'LRC') THEN 'Renewal'
        ELSE 'N/A'
    END AS "COMMISSION TAG",
    FH_FILENAME,
    TO_TIMESTAMP(FH_TIMESTAMP) AS FH_TIMESTAMP
FROM {{ source('ren_comm', 'empire') }}