{{ config(alias='empire', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}} 

SELECT
    DATE("DATE GENERATED") AS DATE_GENERATED,
    TRIM("PRODUCER ID") AS PRODUCER_ID,
    TRIM("PRODUCER SURNAME") AS PRODUCER_SURNAME,
    CASE
        WHEN TRIM("PRODUCER NAME") = 'nan' THEN NULL
        ELSE TRIM("PRODUCER NAME")
    END AS PRODUCER_NAME,     
    CASE
        WHEN TRIM("POLICY OWNER LAST NAME") = 'nan' THEN NULL
        ELSE TRIM("POLICY OWNER LAST NAME")
    END AS POLICY_OWNER_LAST_NAME,
    CASE
        WHEN TRIM("POLICY OWNER FIRST NAME") = 'nan' THEN NULL
        ELSE TRIM("POLICY OWNER FIRST NAME")
    END AS POLICY_OWNER_FIRST_NAME,
    CASE
        WHEN TRIM("POLICY NUMBER") = 'nan' THEN NULL
        ELSE TRIM("POLICY NUMBER")
    END AS POLICY_NUMBER,
    CASE
        WHEN TRIM("CVG INSURED LAST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED LAST NAME")
    END AS CVG_INSURED_LAST_NAME,
    CASE 
        WHEN TRIM("CVG INSURED FIRST NAME") = 'nan' THEN NULL
        ELSE TRIM("CVG INSURED FIRST NAME")
    END AS CVG_INSURED_FIRST_NAME,
    "COVERAGE NUMBER" AS COVERAGE_NUMBER,
    CASE 
        WHEN TRIM("PRODUCT CODE") = 'nan' THEN NULL
        ELSE TRIM("PRODUCT CODE")
    END AS PRODUCT_CODE,
    CASE
        WHEN TRIM("PRODUCT NAME") = 'nan' THEN NULL
        ELSE TRIM("PRODUCT NAME")
    END AS PRODUCT_NAME,
    DATE("ISSUE DT.") AS ISSUE_DATE,
    CASE 
        WHEN TRIM("MODE") = 'nan' THEN NULL
        ELSE TRIM("MODE")
    END AS MODE,
    TRIM("COMM. TYPE") AS COMMISSION_TYPE,
    COMMISSIONABLE_AMT AS COMMISSIONABLE_AMOUNT,
    "COMMISSION RATE" AS COMMISSION_RATE,
    "COMM. AMT" AS COMMISSION_AMOUNT,
    SHARE,
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR")
    END AS OTHER_IMPACTED_PRDCR,
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR SURNAME") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR SURNAME")
    END AS OTHER_IMPACTED_PRDCR_SURNAME,
    CASE
        WHEN TRIM("OTHER IMPACTED PRDCR NAME") = 'nan' THEN NULL
        ELSE TRIM("OTHER IMPACTED PRDCR NAME")
    END AS OTHER_IMPACTED_PRDCR_NAME,    
    TRIM("ISSUE LOCATION") AS ISSUE_LOCATION,
    FH_FILENAME,
    TO_TIMESTAMP(FH_TIMESTAMP) AS FH_TIMESTAMP
FROM {{ source('ren_comm', 'empire') }}