{{ config(alias='empire', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}} 

SELECT
    DATE("DATE GENERATED") AS DATE_GENERATED,
    TRIM("PRODUCER ID") AS PRODUCER_ID,
    TRIM("PRODUCER SURNAME") AS PRODUCER_SURNAME,
    TRIM("PRODUCER NAME") AS PRODUCER_NAME,
    TRIM("POLICY OWNER LAST NAME") AS POLICY_OWNER_LAST_NAME,
    TRIM("POLICY OWNER FIRST NAME") AS POLICY_OWNER_FIRST_NAME,
    TRIM("POLICY NUMBER") AS POLICY_NUMBER,
    TRIM("CVG INSURED LAST NAME") AS CVG_INSURED_LAST_NAME,
    TRIM("CVG INSURED FIRST NAME") AS CVG_INSURED_FIRST_NAME,
    "COVERAGE NUMBER" AS COVERAGE_NUMBER,
    TRIM("PRODUCT CODE") AS PRODUCT_CODE,
    TRIM("PRODUCT NAME") AS PRODUCT_NAME,
    DATE("ISSUE DT.") AS ISSUE_DATE,
    TRIM("MODE") AS MODE,
    TRIM("COMM. TYPE") AS COMMISSION_TYPE,
    COMMISSIONABLE_AMT AS COMMISSIONABLE_AMOUNT,
    "COMMISSION RATE" AS COMMISSION_RATE,
    "COMM. AMT" AS COMMISSION_AMOUNT,
    SHARE,
    TRIM("OTHER IMPACTED PRDCR") AS OTHER_IMPACTED_PRDCR,
    TRIM("OTHER IMPACTED PRDCR SURNAME") AS OTHER_IMPACTED_PRDCR_SURNAME,
    TRIM("OTHER IMPACTED PRDCR NAME") AS OTHER_IMPACTED_PRDCR_NAME,
    TRIM("ISSUE LOCATION") AS ISSUE_LOCATION,
    FH_FILENAME,
    TO_TIMESTAMP(FH_TIMESTAMP) AS FH_TIMESTAMP
FROM {{ source('ren_comm', 'empire') }}