{{ config(alias='ia', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}} 

SELECT
    TRIM(TRANSREFGUID) AS TRANSREFGUID,
    TRIM(TRANSTYPE) AS TRANSTYPE,
    TRANSTYPE_TC,
    CASE
        WHEN TRANSEXEDATE = 'None' THEN NULL
        ELSE TO_DATE(TRANSEXEDATE)
    END AS TRANSEXEDATE,    
    TRANSEXETIME,
    CASE
        WHEN CREATIONDATE = 'None' THEN NULL
        ELSE TO_DATE(CREATIONDATE)
    END AS CREATIONDATE,   
    CREATIONTIME,
    TRIM(SOURCEINFONAME) AS SOURCEINFONAME,
    TRIM(SOURCEINFODESCRIPTION) AS SOURCEINFODESCRIPTION,
    TRIM(STATEMENTTYPE) AS STATEMENTTYPE,
    STATEMENTTYPE_TC,
    CASE
        WHEN STARTDATE = 'None' THEN NULL
        ELSE TO_DATE(STARTDATE)
    END AS STARTDATE,    
    CASE
        WHEN ENDDATE = 'None' THEN NULL
        ELSE TO_DATE(ENDDATE)
    END AS ENDDATE,   
    REMITTANCEAMT,
    CARRIERCODE,
    COMMISSIONTYPE_TC,
    COMMISSIONTRANSACTIONTYPE_TC,
    CASE
        WHEN TRANSACTIONDATE = 'None' THEN NULL
        ELSE TO_DATE(TRANSACTIONDATE)
    END AS TRANSACTIONDATE,    
    CASE
        WHEN COMMISSIONRATE = 'None' THEN NULL
        ELSE COMMISSIONRATE
    END AS COMMISSIONRATE,
    CASE
        WHEN SPLITPERCENT = 'None' THEN NULL
        ELSE SPLITPERCENT
    END AS SPLITPERCENT,    
    CASE
        WHEN PAYMENTBASISAMT = 'None' THEN NULL
        ELSE PAYMENTBASISAMT
    END AS PAYMENTBASISAMT,
    CASE
        WHEN PAYMENTRATECATEGORY_TC = 'None' THEN NULL
        ELSE PAYMENTRATECATEGORY_TC
    END AS PAYMENTRATECATEGORY_TC,   
    TRIM(DESCRIPTION) AS DESCRIPTION,
    PAIDAMT,
    CASE
        WHEN POLNUMBER = 'None' THEN NULL
        ELSE POLNUMBER
    END AS POLNUMBER,    
    TRIM(WRITINGPRODUCERID) AS WRITINGPRODUCERID,
    TRIM(PAIDPRODUCERID) AS PAIDPRODUCERID,
    CASE
        WHEN ACTUALOBJECTTYPE_TC = 'None' THEN NULL
        ELSE ACTUALOBJECTTYPE_TC
    END AS ACTUALOBJECTTYPE_TC,
    CASE
        WHEN ACTUALPRODUCTCODE = 'None' THEN NULL
        ELSE ACTUALPRODUCTCODE
    END AS ACTUALPRODUCTCODE,   
    CASE
        WHEN ACTUALEFFDATE = 'None' THEN NULL
        ELSE TO_DATE(ACTUALEFFDATE)
    END AS ACTUALEFFDATE,    
    CASE
        WHEN CLIENTNAME = 'None' THEN NULL
        ELSE CLIENTNAME
    END AS CLIENTNAME,
    CASE
        WHEN SECONDARYPRODUCTCODE = 'None' THEN NULL
        ELSE SECONDARYPRODUCTCODE
    END AS SECONDARYPRODUCTCODE,
    CASE
        WHEN RESIDENCESTATE_TC = 'None' THEN NULL
        ELSE RESIDENCESTATE_TC
    END AS RESIDENCESTATE_TC,
    CASE
        WHEN DURATION = 'None' THEN NULL
        ELSE DURATION
    END AS DURATION,    
    FH_FILENAME, 
    TO_TIMESTAMP(FH_TIMESTAMP) AS FH_TIMESTAMP
FROM {{ source('ren_comm', 'ia') }}
