{{ config(alias='ivari', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}} 

SELECT
    TRIM("BRANCH CODE") AS BRANCH_CODE,
    TRIM("BRANCH NAME") AS BRANCH_NAME,
    TRIM("ADVISOR CODE") AS ADVISOR_CODE,
    TRIM("ADVISOR NAME") AS ADVISOR_NAME,
    TRIM("COMMISSION TYPE") AS COMMISSION_TYPE,
    DATE("TRANSACTION DATE") AS TRANSACTION_DATE,    
    CASE 
        WHEN TRIM(POLICY) = 'nan' THEN NULL
        ELSE TRIM(POLICY)
    END AS POLICY_NUMBER,    
    TRIM("COVERAGE#") AS COVERAGE_NUMBER,
    CASE
        WHEN TRIM("PLAN DESCRIPTION") = 'nan' THEN NULL
        ELSE TRIM("PLAN DESCRIPTION")        
    END AS PLAN_DESCRIPTION,
    CASE
        WHEN TRIM("INSURED NAME") = 'nan' THEN NULL
        ELSE TRIM("INSURED NAME")
    END AS INSURED_NAME,
    "BASIS AMOUNT" AS BASIS_AMOUNT,
    "SHARE %" AS SHARE_PERCENT,
    "COMP RATE %" AS COMP_RATE_PERCENT,
    "COMP AMOUNT" AS COMP_AMOUNT,
    CASE
        WHEN TRIM("FROM/TO ADVISOR") = 'nan' THEN NULL
        ELSE TRIM("FROM/TO ADVISOR")
    END AS FROM_TO_ADVISOR,
    CASE
        WHEN TRIM("FROM/TO ADVISOR NAME") = 'nan' THEN NULL
        ELSE TRIM("FROM/TO ADVISOR NAME")
    END AS FROM_TO_ADVISOR_NAME,
    FH_FILENAME, 
    TO_TIMESTAMP(FH_TIMESTAMP) AS FH_TIMESTAMP
FROM {{ source('ren_comm', 'ivari') }}