{{ config(alias='manulife', 
    database='integrate_comm', 
    schema='extracts', 
    materialization = "view",
    grants = {'ownership': ['COMMISSION']},)  
}}


SELECT
    'Manulife' as "COMPANY",
    "DISTRIBUTOR"::STRING as "DISTRIBUTOR CODE",
    CAST("MANULIFE SELLING CODE" as VARCHAR) as "AGENT SELLING CODE",
    "POLICY",
    "FIRST NAME",
    "LAST NAME",
    DATE("GENERATION DATE") AS "GENERATION DATE",
    "COMMISSION TYPE",
    LEFT("COMMISSION TYPE", POSITION(' ' in "COMMISSION TYPE") - 1) AS  "COMMISSION SUBTYPE",
    "MODE",
    "FASAT DIVISION" AS "DIVISION",
    "FASAT LINE OF BUSINESS" AS "LINE OF BUSINESS",
    "FASAT PRODUCT" AS "PRODUCT",
    CAST("BASIC PLAN CODE" AS VARCHAR) as "BASIC PLAN CODE",
    "COMMISSION RATE",
    "STATEMENT BASIS AMOUNT",
    "AMOUNT",
    "SHARE %" as "SHARE %",
    "OVERRIDE COMMISSION AMOUNT",
    "COMMISSIONABLE PREMIUM",
    COALESCE("FROM/TO ADVISOR"::TEXT, '') AS "FROM/TO ADVISOR",
    COALESCE("ORIGINAL ADVISOR"::TEXT, '') as "ORIGINAL ADVISOR",
    "BUSINESS FIRST NAME",
    "BUSINESS SURNAME",
    DATE("PROCESSED DATE") AS "PROCESSED DATE",
    CASE
        WHEN LEFT("COMMISSION TYPE", POSITION(' ' in "COMMISSION TYPE") - 1) IN ('FYC', 'FOV', 'EOV', 'EFY') THEN 'First Year'
        WHEN LEFT("COMMISSION TYPE", POSITION(' ' in "COMMISSION TYPE") - 1) IN ('REN', 'ROV') THEN 'Renewal'
        WHEN LEFT("COMMISSION TYPE", POSITION(' ' in "COMMISSION TYPE") - 1) IN ('DEB') THEN 'Debt'
        WHEN LEFT("COMMISSION TYPE", POSITION(' ' in "COMMISSION TYPE") - 1) IN ('MSC') THEN 'Other'
        ELSE 'N/A'
    END AS "COMMISSION TAG",
    TRIM(FH_FILENAME) AS FH_FILENAME, 
    FH_TIMESTAMP
FROM {{ source('ren_comm', 'manulife') }}
