{{ config(
    alias='rbc', 
    database='integrate_comm', 
    schema='extracts', 
    materialized='view',
    grants={'ownership': ['COMMISSION']},
) }} 

SELECT
    "ADVISOR'S CODE" AS ADVISOR_CODE,
    "BUS. REPORTING NAME" AS BUS_REPORTING_NAME,
    "FIRST NAME" AS FIRST_NAME,
    "LAST NAME" AS LAST_NAME,
    POLICY,
    GSI,
    "DISCOUNT TYPE" AS DISCOUNT_TYPE,
    "PRODUCT TYPE" AS PRODUCT_TYPE,
    "PLAN CODE SHORT DESC." AS PLAN_CODE_SHORT_DESC,
    "COMM. TYPE" AS COMM_TYPE,
    DATE(DATE) AS DATE,
    MODE,
    "POLICY YEAR" AS POLICY_YEAR,
    "COMPENSATION BASE AMOUNT" AS COMPENSATION_BASE_AMOUNT,
    SHARE,
    RATE,
    "CHARGEBACK RATE" AS CHARGEBACK_RATE,
    AMOUNT,
    DATE("STATEMENT DATE") AS STATEMENT_DATE,
    "REPORTING ROUTING PATH" AS REPORTING_ROUTING_PATH,
    TOP,
    --"UNNAMED: 21",
    DATE("GENERATION DATE") AS GENERATION_DATE,
    FH_FILENAME,
    FH_TIMESTAMP
FROM
    {{ source('ren_comm', 'rbc') }}