{{
    config(
        materialized="view",
        alias="__base_put_on_one_row_disability",
        database="integrate",
        schema="insurance",
        grants={"ownership": ["FH_READER"]}
    )
}}

WITH STARTING_DATA AS (
    SELECT
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        ADVISOR_AGREEMENT_NUMBER,
        ADVISOR_REPORTING_FIRM_NAME,
        AC_REGION,
        AC_MARKET,
        AC_LOCATION,
        PRODUCT_KIND,
        PRODUCT_TYPE,
        CURRENT_CONTRACT_POLICY_NUMBER,
        CARRIER,
        CURRENT_POLICY_STATUS,
        SETTLEMENT_DATE,
        APPLICATION_DATE,
        FIRST_COMMISSION_DATE,
        PLACED_TOTAL_SALES_MEASURE,
        PENDING_DECIDED_TOTAL_SALES_MEASURE,
        SALES_COUNT_CREDIT,
        PLACED_POLICY_COUNT,
        PENDING_POLICY_COUNT,
        FYC_AMOUNT
    FROM
        {{ ref('__base_put_on_one_row_integrate_insurance') }}
),
RECS_TO_CORRECT_FYC AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        PRODUCT_KIND,
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        SUM(PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        MAX(SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        MAX(PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        MAX(PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        SUM(FYC_AMOUNT) AS FYC_AMOUNT
    FROM
        STARTING_DATA
    WHERE
        PRODUCT_TYPE in ('-', 'Other')
        AND PRODUCT_KIND = 'Disability'
    GROUP BY
        1,2,3,4
    HAVING
        SUM(PLACED_TOTAL_SALES_MEASURE) = 0
        AND SUM(FYC_AMOUNT) > 0
    ORDER BY
        1,2,3,4
),
RECS_TO_CORRECT_PREM AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        PRODUCT_KIND,
        PRODUCT_TYPE,
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        SUM(PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        MAX(SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        MAX(PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        MAX(PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        SUM(FYC_AMOUNT) AS FYC_AMOUNT
    FROM
        STARTING_DATA
    WHERE
        CURRENT_CONTRACT_POLICY_NUMBER in (
            SELECT
                DISTINCT CURRENT_CONTRACT_POLICY_NUMBER
            FROM
                RECS_TO_CORRECT_FYC
        )
        AND PRODUCT_KIND = 'Disability'
    GROUP BY
        1,2,3,4,5
    HAVING
        SUM(PLACED_TOTAL_SALES_MEASURE) > 0
        AND SUM(FYC_AMOUNT) = 0
    ORDER BY
        1,2,3,4
),
CORRECTIONS AS (
    SELECT
        FYC.CURRENT_CONTRACT_POLICY_NUMBER,
        FYC.PRODUCT_KIND,
        PREM.PRODUCT_TYPE,
        FYC.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        FYC.ADVISOR_PRODUCER_NAME,
        PREM.PLACED_TOTAL_SALES_MEASURE,
        PREM.PENDING_DECIDED_TOTAL_SALES_MEASURE,
        PREM.SALES_COUNT_CREDIT,
        PREM.PLACED_POLICY_COUNT,
        PREM.PENDING_POLICY_COUNT,
        FYC.FYC_AMOUNT
    FROM
        RECS_TO_CORRECT_FYC FYC
        LEFT JOIN RECS_TO_CORRECT_PREM PREM ON FYC.CURRENT_CONTRACT_POLICY_NUMBER = PREM.CURRENT_CONTRACT_POLICY_NUMBER
        AND FYC.PRODUCT_KIND = PREM.PRODUCT_KIND
        AND FYC.ADVISOR_PRODUCER_NAME = PREM.ADVISOR_PRODUCER_NAME
),
CORRECTION_RECORDS AS (
    SELECT
        A.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        A.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        A.ADVISOR_PRODUCER_NAME,
        A.ADVISOR_AGREEMENT_NUMBER,
        A.ADVISOR_REPORTING_FIRM_NAME,
        AC_REGION,
        AC_MARKET,
        AC_LOCATION,
        A.PRODUCT_KIND,
        C.PRODUCT_TYPE AS PRODUCT_TYPE,
        A.CURRENT_CONTRACT_POLICY_NUMBER,
        CARRIER,
        CURRENT_POLICY_STATUS,
        SETTLEMENT_DATE,
        APPLICATION_DATE,
        FIRST_COMMISSION_DATE,
        ROUND(SUM(A.PLACED_TOTAL_SALES_MEASURE), 2) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(A.PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        SUM(A.SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        SUM(A.PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        SUM(A.PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        ROUND(SUM(C.FYC_AMOUNT), 2) AS FYC_AMOUNT
    FROM
        STARTING_DATA A
        JOIN CORRECTIONS C ON A.CURRENT_CONTRACT_POLICY_NUMBER = C.CURRENT_CONTRACT_POLICY_NUMBER
        AND A.PRODUCT_TYPE = C.PRODUCT_TYPE
        AND A.ADVISOR_AGREEMENT_GROUP_IDENTIFIER = C.ADVISOR_AGREEMENT_GROUP_IDENTIFIER
    GROUP BY
        1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
),
CORRECTED_RECORDS_PREM_REC_DROPPED AS (
    SELECT
        C_REC.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        C_REC.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        C_REC.ADVISOR_PRODUCER_NAME,
        C_REC.ADVISOR_AGREEMENT_GROUP_IDENTIFIER AS ADVISOR_AGREEMENT_NUMBER,
        C_REC.ADVISOR_REPORTING_FIRM_NAME,
        C_REC.AC_REGION,
        C_REC.AC_MARKET,
        C_REC.AC_LOCATION,
        C_REC.PRODUCT_KIND,
        C_REC.PRODUCT_TYPE,
        C_REC.CURRENT_CONTRACT_POLICY_NUMBER,
        C_REC.CARRIER,
        C_REC.CURRENT_POLICY_STATUS,
        C_REC.SETTLEMENT_DATE,
        C_REC.APPLICATION_DATE,
        C_REC.FIRST_COMMISSION_DATE,
        ROUND(CORRECTIONS.PLACED_TOTAL_SALES_MEASURE, 2) AS PLACED_TOTAL_SALES_MEASURE,
        CORRECTIONS.PENDING_DECIDED_TOTAL_SALES_MEASURE,
        CORRECTIONS.SALES_COUNT_CREDIT,
        CORRECTIONS.PLACED_POLICY_COUNT,
        CORRECTIONS.PENDING_POLICY_COUNT,
        CORRECTIONS.FYC_AMOUNT
    FROM
        CORRECTION_RECORDS C_REC
        JOIN CORRECTIONS on C_REC.CURRENT_CONTRACT_POLICY_NUMBER = CORRECTIONS.CURRENT_CONTRACT_POLICY_NUMBER
        AND C_REC.PRODUCT_TYPE = CORRECTIONS.PRODUCT_TYPE
        AND C_REC.PRODUCT_KIND = CORRECTIONS.PRODUCT_KIND
        AND C_REC.ADVISOR_PRODUCER_NAME = CORRECTIONS.ADVISOR_PRODUCER_NAME
    WHERE
        C_REC.FYC_AMOUNT != 0
    GROUP BY
        ALL 
) 
SELECT
    ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    ADVISOR_PRODUCER_NAME,
    ADVISOR_AGREEMENT_NUMBER,
    ADVISOR_REPORTING_FIRM_NAME,
    AC_REGION,
    AC_MARKET,
    AC_LOCATION,
    PRODUCT_KIND,
    PRODUCT_TYPE,
    CURRENT_CONTRACT_POLICY_NUMBER,
    CARRIER,
    CURRENT_POLICY_STATUS,
    SETTLEMENT_DATE,
    APPLICATION_DATE,
    FIRST_COMMISSION_DATE,
    PLACED_TOTAL_SALES_MEASURE,
    PENDING_DECIDED_TOTAL_SALES_MEASURE,
    SALES_COUNT_CREDIT,
    PLACED_POLICY_COUNT,
    PENDING_POLICY_COUNT,
    FYC_AMOUNT
FROM
    CORRECTED_RECORDS_PREM_REC_DROPPED
UNION
SELECT
    STARTING_DATA.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    STARTING_DATA.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    STARTING_DATA.ADVISOR_PRODUCER_NAME,
    STARTING_DATA.ADVISOR_AGREEMENT_NUMBER,
    STARTING_DATA.ADVISOR_REPORTING_FIRM_NAME,
    STARTING_DATA.AC_REGION,
    STARTING_DATA.AC_MARKET,
    STARTING_DATA.AC_LOCATION,
    STARTING_DATA.PRODUCT_KIND,
    STARTING_DATA.PRODUCT_TYPE,
    STARTING_DATA.CURRENT_CONTRACT_POLICY_NUMBER,
    STARTING_DATA.CARRIER,
    STARTING_DATA.CURRENT_POLICY_STATUS,
    STARTING_DATA.SETTLEMENT_DATE,
    STARTING_DATA.APPLICATION_DATE,
    STARTING_DATA.FIRST_COMMISSION_DATE,
    SUM(STARTING_DATA.PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
    SUM(
        STARTING_DATA.PENDING_DECIDED_TOTAL_SALES_MEASURE
    ) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
    SUM(STARTING_DATA.SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
    SUM(STARTING_DATA.PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
    SUM(STARTING_DATA.PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
    SUM(STARTING_DATA.FYC_AMOUNT) AS FYC_AMOUNT
FROM
    STARTING_DATA
    LEFT JOIN CORRECTION_RECORDS on CORRECTION_RECORDS.CURRENT_CONTRACT_POLICY_NUMBER = STARTING_DATA.CURRENT_CONTRACT_POLICY_NUMBER
    AND CORRECTION_RECORDS.PRODUCT_KIND = STARTING_DATA.PRODUCT_KIND
    AND CORRECTION_RECORDS.ADVISOR_AGREEMENT_GROUP_IDENTIFIER = STARTING_DATA.ADVISOR_AGREEMENT_GROUP_IDENTIFIER
WHERE
    CORRECTION_RECORDS.CURRENT_CONTRACT_POLICY_NUMBER IS NULL
GROUP BY
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16