{{
    config(
        materialized="view",
        alias="__base_add_back_advisor_agreement_number",
        database="integrate",
        schema="insurance",
        grants={"ownership": ["FH_READER"]}
    )
}}

WITH REVISED_MAPPING_TABLE AS (
    SELECT
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        CURRENT_CONTRACT_POLICY_NUMBER,
        ADVISOR_PRODUCER_NAME,
        FIRST_VALUE(ADVISOR_AGREEMENT_NUMBER) OVER (
            PARTITION BY ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
            CURRENT_CONTRACT_POLICY_NUMBER,
            ADVISOR_PRODUCER_NAME
            ORDER BY
                ADVISOR_AGREEMENT_NUMBER NULLS LAST
        ) AS ADVISOR_AGREEMENT_NUMBER
    FROM
        {{ ref('daily_insurance_policy_cl_detail') }}
),
REVISED_MAPPING_TABLE_V2 AS (
    SELECT
        *
    FROM
        REVISED_MAPPING_TABLE
    GROUP BY
        ALL
)
SELECT
    D.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    D.ADVISOR_PRODUCER_NAME,
    M.ADVISOR_AGREEMENT_NUMBER,
    ADVISOR_REPORTING_FIRM_NAME,
    AC_REGION,
    AC_MARKET,
    AC_LOCATION,
    PRODUCT_KIND,
    PRODUCT_TYPE,
    D.CURRENT_CONTRACT_POLICY_NUMBER,
    CARRIER,
    CURRENT_POLICY_STATUS,
    SETTLEMENT_DATE,
    APPLICATION_DATE,
    FIRST_COMMISSION_DATE,
    PLACED_TOTAL_SALES_MEASURE,
    PENDING_DECIDED_TOTAL_SALES_MEASURE,
    SALES_COUNT_CREDIT,
    PLACED_POLICY_COUNT,
    PENDING_POLICY_COUNT,
    FYC_AMOUNT
FROM
    {{ ref('__base_put_on_one_row_disability_integrate_insurance') }} D
    LEFT JOIN REVISED_MAPPING_TABLE_V2 M ON D.ADVISOR_AGREEMENT_GROUP_IDENTIFIER = M.ADVISOR_AGREEMENT_GROUP_IDENTIFIER
    AND D.CURRENT_CONTRACT_POLICY_NUMBER = M.CURRENT_CONTRACT_POLICY_NUMBER
    AND D.ADVISOR_PRODUCER_NAME = M.ADVISOR_PRODUCER_NAME