{{
    config(
        materialized="view",
        alias="__base_CL_Data",
        database="integrate",
        schema="insurance",
        grants={"ownership": ["FH_READER"]}
    )
}}

WITH

CL_EXTRACT AS (
    SELECT
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        ADVISOR_AGREEMENT_NUMBER,
        ADVISOR_REPORTING_FIRM_NAME,
        AC_REGION,
        AC_MARKET,
        AC_LOCATION,
        PRODUCT_KIND,
        PRODUCT_TYPE,
        CURRENT_CONTRACT_POLICY_NUMBER,
        CARRIER,
        CURRENT_POLICY_STATUS,
        SETTLEMENT_DATE,
        PLACED_TOTAL_SALES_MEASURE,
        PENDING_DECIDED_TOTAL_SALES_MEASURE,
        SALES_COUNT_CREDIT,
        PLACED_POLICY_COUNT,
        PENDING_POLICY_COUNT,
        FYC_AMOUNT,
        CASE
            WHEN APPLICATION_DATE = '9999-12-31' THEN '2024-01-01' ELSE
                APPLICATION_DATE
        END AS APPLICATION_DATE,
        CASE
            WHEN
                FIRST_COMMISSION_DATE = '9999-12-31'
                THEN COALESCE(SETTLEMENT_DATE, null)
            ELSE FIRST_COMMISSION_DATE
        END AS FIRST_COMMISSION_DATE,
        CONCAT(PRODUCT_KIND, '-', PRODUCT_TYPE) AS CVG_NAME
    FROM {{ ref('daily_insurance_policy_cl_detail') }}
),

FH_APP_COUNT AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER AS POLICYNUMBER,
        1 AS R,
        COUNT(DISTINCT ADVISOR_AGREEMENT_NUMBER) AS C
    FROM {{ ref('daily_insurance_policy_cl_detail') }}
    GROUP BY 1
),

CL_DATA_WITH_CVG AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        ADVISOR_AGREEMENT_NUMBER,
        CONCAT(PRODUCT_KIND, '-', PRODUCT_TYPE) AS CVG_NAME,
        ROW_NUMBER()
            OVER (
                PARTITION BY
                    CURRENT_CONTRACT_POLICY_NUMBER, ADVISOR_AGREEMENT_NUMBER
                ORDER BY
                    CONCAT(PRODUCT_KIND, '-', PRODUCT_TYPE)
            ) AS COVERAGE_NUMBER
    FROM {{ ref('daily_insurance_policy_cl_detail') }}
    GROUP BY 1, 2, 3
),

CL_DATA_WITH_RANK_WGT AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        ADVISOR_AGREEMENT_NUMBER,
        1 / FH_APP_COUNT.C AS APPCOUNT
    FROM CL_DATA_WITH_CVG
    INNER JOIN
        FH_APP_COUNT
        ON
            CL_DATA_WITH_CVG.CURRENT_CONTRACT_POLICY_NUMBER
            = FH_APP_COUNT.POLICYNUMBER
    GROUP BY ALL
),



CL_DATA_WHOLE_TABLE_W_CVG_NUM AS (
    SELECT
        CL_EXTRACT.*,
        CVG.COVERAGE_NUMBER,
        W.APPCOUNT AS FH_APPCOUNT
    FROM CL_EXTRACT
    LEFT JOIN CL_DATA_WITH_CVG AS CVG
        ON
            CL_EXTRACT.CURRENT_CONTRACT_POLICY_NUMBER
            = CVG.CURRENT_CONTRACT_POLICY_NUMBER
            AND CL_EXTRACT.CVG_NAME = CVG.CVG_NAME
            AND CL_EXTRACT.ADVISOR_AGREEMENT_NUMBER
            = CVG.ADVISOR_AGREEMENT_NUMBER
    LEFT JOIN CL_DATA_WITH_RANK_WGT AS W
        ON
            CL_EXTRACT.CURRENT_CONTRACT_POLICY_NUMBER
            = W.CURRENT_CONTRACT_POLICY_NUMBER
            AND CL_EXTRACT.ADVISOR_AGREEMENT_NUMBER
            = W.ADVISOR_AGREEMENT_NUMBER
    WHERE COVERAGE_NUMBER = 1

    UNION

    SELECT
        CL_EXTRACT.*,
        CVG.COVERAGE_NUMBER,
        0 AS FH_APPCOUNT
    FROM CL_EXTRACT
    LEFT JOIN CL_DATA_WITH_CVG AS CVG
        ON
            CL_EXTRACT.CURRENT_CONTRACT_POLICY_NUMBER
            = CVG.CURRENT_CONTRACT_POLICY_NUMBER
            AND CL_EXTRACT.CVG_NAME = CVG.CVG_NAME
            AND CL_EXTRACT.ADVISOR_AGREEMENT_NUMBER
            = CVG.ADVISOR_AGREEMENT_NUMBER
    LEFT JOIN CL_DATA_WITH_RANK_WGT AS W
        ON
            CL_EXTRACT.CURRENT_CONTRACT_POLICY_NUMBER
            = W.CURRENT_CONTRACT_POLICY_NUMBER
            AND CL_EXTRACT.ADVISOR_AGREEMENT_NUMBER
            = W.ADVISOR_AGREEMENT_NUMBER
    WHERE COVERAGE_NUMBER > 1
)

SELECT
    ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    ADVISOR_PRODUCER_NAME,
    ADVISOR_AGREEMENT_NUMBER,
    ADVISOR_REPORTING_FIRM_NAME,
    AC_REGION,
    AC_MARKET,
    AC_LOCATION,
    PRODUCT_KIND,
    PRODUCT_TYPE,
    CURRENT_CONTRACT_POLICY_NUMBER,
    CARRIER,
    CURRENT_POLICY_STATUS,
    SETTLEMENT_DATE,
    APPLICATION_DATE,
    FIRST_COMMISSION_DATE,
    PLACED_TOTAL_SALES_MEASURE,
    PENDING_DECIDED_TOTAL_SALES_MEASURE,
    FYC_AMOUNT,
    CVG_NAME,
    COVERAGE_NUMBER,
    FH_APPCOUNT,
    CASE WHEN CURRENT_POLICY_STATUS = '-' THEN 0 ELSE SALES_COUNT_CREDIT END
        AS SALES_COUNT_CREDIT,
    CASE WHEN CURRENT_POLICY_STATUS = '-' THEN 0 ELSE PLACED_POLICY_COUNT END
        AS PLACED_POLICY_COUNT,
    CASE WHEN CURRENT_POLICY_STATUS = '-' THEN 0 ELSE PENDING_POLICY_COUNT END
        AS PENDING_POLICY_COUNT
FROM CL_DATA_WHOLE_TABLE_W_CVG_NUM
