{{
    config(
        materialized="view",
        alias="__base_put_on_one_row",
        database="integrate",
        schema="insurance",
        grants={"ownership": ["FH_READER"]}
    )
}}

WITH CORR_PRODUCT_KIND AS (
    SELECT
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        '' AS ADVISOR_AGREEMENT_NUMBER,
        ADVISOR_REPORTING_FIRM_NAME,
        AC_REGION,
        AC_MARKET,
        AC_LOCATION,
        CASE
            WHEN PK.REVISED_PRODUCT_KIND IS NOT NULL THEN PK.REVISED_PRODUCT_KIND
            ELSE PRODUCT_KIND
        END AS PRODUCT_KIND,
        PRODUCT_TYPE,
        RAW_DATA.CURRENT_CONTRACT_POLICY_NUMBER,
        CARRIER,
        CURRENT_POLICY_STATUS,
        SETTLEMENT_DATE,
        APPLICATION_DATE,
        FIRST_COMMISSION_DATE,
        PLACED_TOTAL_SALES_MEASURE,
        PENDING_DECIDED_TOTAL_SALES_MEASURE,
        SALES_COUNT_CREDIT,
        PLACED_POLICY_COUNT,
        PENDING_POLICY_COUNT,
        FYC_AMOUNT
    FROM
        {{ ref('daily_insurance_policy_cl_detail') }} RAW_DATA
        LEFT JOIN {{ ref('__base_correct_product_kind') }} PK on raw_data.CURRENT_CONTRACT_POLICY_NUMBER = PK.CURRENT_CONTRACT_POLICY_NUMBER
),
RECS_TO_CORRECT_FYC AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        PRODUCT_KIND,
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        SUM(PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        MAX(SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        MAX(PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        MAX(PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        SUM(FYC_AMOUNT) AS FYC_AMOUNT
    FROM
        CORR_PRODUCT_KIND
    GROUP BY
        1, 2, 3, 4
    HAVING
        SUM(PLACED_TOTAL_SALES_MEASURE) = 0
        AND SUM(FYC_AMOUNT) > 0
    ORDER BY
        1, 2, 3, 4
),
RECS_TO_CORRECT_PREM AS (
    SELECT
        CURRENT_CONTRACT_POLICY_NUMBER,
        PRODUCT_KIND,
        ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        ADVISOR_PRODUCER_NAME,
        SUM(PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        MAX(SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        MAX(PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        MAX(PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        SUM(FYC_AMOUNT) AS FYC_AMOUNT
    FROM
        CORR_PRODUCT_KIND
    GROUP BY
        1, 2, 3, 4
    HAVING
        SUM(PLACED_TOTAL_SALES_MEASURE) > 0
        AND SUM(FYC_AMOUNT) = 0
    ORDER BY
        1, 2, 3, 4
),
CORRECTIONS AS (
    SELECT
        FYC.CURRENT_CONTRACT_POLICY_NUMBER,
        FYC.PRODUCT_KIND,
        FYC.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        FYC.ADVISOR_PRODUCER_NAME,
        PREM.PLACED_TOTAL_SALES_MEASURE,
        PREM.PENDING_DECIDED_TOTAL_SALES_MEASURE,
        PREM.SALES_COUNT_CREDIT,
        PREM.PLACED_POLICY_COUNT,
        PREM.PENDING_POLICY_COUNT,
        FYC.FYC_AMOUNT
    FROM
        RECS_TO_CORRECT_FYC FYC
        JOIN RECS_TO_CORRECT_PREM PREM ON FYC.CURRENT_CONTRACT_POLICY_NUMBER = PREM.CURRENT_CONTRACT_POLICY_NUMBER
        AND FYC.PRODUCT_KIND = PREM.PRODUCT_KIND
),
CORRECTION_RECORDS AS (
    SELECT
        A.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        A.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        A.ADVISOR_PRODUCER_NAME,
        A.ADVISOR_AGREEMENT_NUMBER,
        A.ADVISOR_REPORTING_FIRM_NAME,
        AC_REGION,
        AC_MARKET,
        AC_LOCATION,
        A.PRODUCT_KIND,
        '-' AS PRODUCT_TYPE,
        A.CURRENT_CONTRACT_POLICY_NUMBER,
        CARRIER,
        CURRENT_POLICY_STATUS,
        SETTLEMENT_DATE,
        APPLICATION_DATE,
        FIRST_COMMISSION_DATE,
        SUM(A.PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
        SUM(A.PENDING_DECIDED_TOTAL_SALES_MEASURE) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
        SUM(A.SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
        SUM(A.PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
        SUM(A.PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
        SUM(A.FYC_AMOUNT) AS FYC_AMOUNT
    FROM
        CORR_PRODUCT_KIND A
        JOIN CORRECTIONS C ON a.CURRENT_CONTRACT_POLICY_NUMBER = C.CURRENT_CONTRACT_POLICY_NUMBER
        AND A.PRODUCT_KIND = C.PRODUCT_KIND
    GROUP BY
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
        
    HAVING
        (
            ROUND(SUM(A.FYC_AMOUNT)) = 0
            AND ROUND(SUM(A.PLACED_TOTAL_SALES_MEASURE)) != 0
        )
        OR (
            ROUND(SUM(A.FYC_AMOUNT)) != 0
            AND ROUND(SUM(A.PLACED_TOTAL_SALES_MEASURE)) = 0
        )
),
CORRECTED_RECORDS_PREM_REC_DROPPED AS (
    SELECT
        C_REC.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        C_REC.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        C_REC.ADVISOR_PRODUCER_NAME,
        C_REC.ADVISOR_AGREEMENT_NUMBER,
        C_REC.ADVISOR_REPORTING_FIRM_NAME,
        C_REC.AC_REGION,
        C_REC.AC_MARKET,
        C_REC.AC_LOCATION,
        C_REC.PRODUCT_KIND,
        C_REC.PRODUCT_TYPE,
        C_REC.CURRENT_CONTRACT_POLICY_NUMBER,
        C_REC.CARRIER,
        C_REC.CURRENT_POLICY_STATUS,
        C_REC.SETTLEMENT_DATE,
        C_REC.APPLICATION_DATE,
        C_REC.FIRST_COMMISSION_DATE,
        CORRECTIONS.PLACED_TOTAL_SALES_MEASURE,
        CORRECTIONS.PENDING_DECIDED_TOTAL_SALES_MEASURE,
        CORRECTIONS.SALES_COUNT_CREDIT,
        CORRECTIONS.PLACED_POLICY_COUNT,
        CORRECTIONS.PENDING_POLICY_COUNT,
        CORRECTIONS.FYC_AMOUNT
    FROM
        CORRECTION_RECORDS C_REC
        JOIN CORRECTIONS ON C_REC.CURRENT_CONTRACT_POLICY_NUMBER = CORRECTIONS.CURRENT_CONTRACT_POLICY_NUMBER
        AND C_REC.PRODUCT_KIND = CORRECTIONS.PRODUCT_KIND
    WHERE
        C_REC.FYC_AMOUNT != 0
),
MAP_ADVISOR_AGREEMENT_NUMBER_BACK AS (
    SELECT
        C.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
        C.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
        C.ADVISOR_PRODUCER_NAME,
        A.ADVISOR_AGREEMENT_NUMBER,
        C.ADVISOR_REPORTING_FIRM_NAME,
        C.AC_REGION,
        C.AC_MARKET,
        C.AC_LOCATION,
        C.PRODUCT_KIND,
        C.PRODUCT_TYPE,
        C.CURRENT_CONTRACT_POLICY_NUMBER,
        C.CARRIER,
        C.CURRENT_POLICY_STATUS,
        C.SETTLEMENT_DATE,
        C.APPLICATION_DATE,
        C.FIRST_COMMISSION_DATE,
        C.PLACED_TOTAL_SALES_MEASURE,
        C.PENDING_DECIDED_TOTAL_SALES_MEASURE,
        C.SALES_COUNT_CREDIT,
        C.PLACED_POLICY_COUNT,
        C.PENDING_POLICY_COUNT,
        C.FYC_AMOUNT
    FROM
        CORRECTED_RECORDS_PREM_REC_DROPPED C
        JOIN {{ ref('daily_insurance_policy_cl_detail') }} A ON C.CURRENT_CONTRACT_POLICY_NUMBER = A.CURRENT_CONTRACT_POLICY_NUMBER
        AND C.ADVISOR_PRODUCER_NAME = A.ADVISOR_PRODUCER_NAME
    GROUP BY
        ALL
)
SELECT
    ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    ADVISOR_PRODUCER_NAME,
    ADVISOR_AGREEMENT_NUMBER,
    ADVISOR_REPORTING_FIRM_NAME,
    AC_REGION,
    AC_MARKET,
    AC_LOCATION,
    PRODUCT_KIND,
    PRODUCT_TYPE,
    CURRENT_CONTRACT_POLICY_NUMBER,
    CARRIER,
    CURRENT_POLICY_STATUS,
    SETTLEMENT_DATE,
    APPLICATION_DATE,
    FIRST_COMMISSION_DATE,
    PLACED_TOTAL_SALES_MEASURE,
    PENDING_DECIDED_TOTAL_SALES_MEASURE,
    SALES_COUNT_CREDIT,
    PLACED_POLICY_COUNT,
    PENDING_POLICY_COUNT,
    FYC_AMOUNT
FROM
    MAP_ADVISOR_AGREEMENT_NUMBER_BACK
UNION
SELECT
    CORR_PRODUCT_KIND.ADVISOR_AGREEMENT_GROUP_IDENTIFIER,
    CORR_PRODUCT_KIND.FINANCIAL_HORIZONS_GROUP_IDENTIFIER,
    CORR_PRODUCT_KIND.ADVISOR_PRODUCER_NAME,
    CORR_PRODUCT_KIND.ADVISOR_AGREEMENT_NUMBER,
    CORR_PRODUCT_KIND.ADVISOR_REPORTING_FIRM_NAME,
    CORR_PRODUCT_KIND.AC_REGION,
    CORR_PRODUCT_KIND.AC_MARKET,
    CORR_PRODUCT_KIND.AC_LOCATION,
    CORR_PRODUCT_KIND.PRODUCT_KIND,
    CORR_PRODUCT_KIND.PRODUCT_TYPE,
    CORR_PRODUCT_KIND.CURRENT_CONTRACT_POLICY_NUMBER,
    CORR_PRODUCT_KIND.CARRIER,
    CORR_PRODUCT_KIND.CURRENT_POLICY_STATUS,
    CORR_PRODUCT_KIND.SETTLEMENT_DATE,
    CORR_PRODUCT_KIND.APPLICATION_DATE,
    CORR_PRODUCT_KIND.FIRST_COMMISSION_DATE,
    SUM(CORR_PRODUCT_KIND.PLACED_TOTAL_SALES_MEASURE) AS PLACED_TOTAL_SALES_MEASURE,
    SUM(
        CORR_PRODUCT_KIND.PENDING_DECIDED_TOTAL_SALES_MEASURE
    ) AS PENDING_DECIDED_TOTAL_SALES_MEASURE,
    SUM(CORR_PRODUCT_KIND.SALES_COUNT_CREDIT) AS SALES_COUNT_CREDIT,
    SUM(CORR_PRODUCT_KIND.PLACED_POLICY_COUNT) AS PLACED_POLICY_COUNT,
    SUM(CORR_PRODUCT_KIND.PENDING_POLICY_COUNT) AS PENDING_POLICY_COUNT,
    SUM(CORR_PRODUCT_KIND.FYC_AMOUNT) AS FYC_AMOUNT
FROM
    CORR_PRODUCT_KIND
    LEFT JOIN CORRECTION_RECORDS ON CORRECTION_RECORDS.CURRENT_CONTRACT_POLICY_NUMBER = CORR_PRODUCT_KIND.CURRENT_CONTRACT_POLICY_NUMBER
    AND CORRECTION_RECORDS.PRODUCT_KIND = CORR_PRODUCT_KIND.PRODUCT_KIND
    AND CORRECTION_RECORDS.ADVISOR_AGREEMENT_GROUP_IDENTIFIER = CORR_PRODUCT_KIND.ADVISOR_AGREEMENT_GROUP_IDENTIFIER
WHERE
    CORRECTION_RECORDS.CURRENT_CONTRACT_POLICY_NUMBER IS NULL
GROUP BY
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16