{{
    config(
        materialized="view",
        alias="policy_fh_cl",
        database="integrate",
        schema="insurance",
        grants={"ownership": ["FH_READER"]}
    )
}}

WITH

POL_WITH_UD2 AS (
    SELECT
        POL_BASE.*,
        B_SERV.USERDEFINED2 AS FH_SERVICINGAGT_UD2,
        B_COMM.USERDEFINED2 AS FH_COMMISSIONINGAGT_UD2
    FROM
        {{ ref('__base_pol_fh_cl_integrate_insurance') }} AS POL_BASE
    LEFT JOIN
        {{ ref('broker_fh_cl_integrate_insurance') }} AS B_COMM
        ON POL_BASE.FH_COMMISSIONINGAGTCODE = B_COMM.AGENTCODE
    LEFT JOIN
        {{ ref('broker_fh_cl_integrate_insurance') }} AS B_SERV
        ON POL_BASE.FH_SERVICINGAGTCODE = B_SERV.AGENTCODE
),


HIER_W_UD2 AS (
    SELECT
        H.*,
        REGEXP_REPLACE(B.USERDEFINED2, '^FH', '') AS UD2
    FROM {{ ref('broker_fh_cl_integrate_insurance') }} AS B
    INNER JOIN
        {{ ref('hierarchy_fh_cl_integrate_insurance') }} AS H
        ON B.AGENTCODE = H.AGENTCODE
),

BROKER_ACTIVE AS (
    SELECT DISTINCT
        B.USERDEFINED2,
        FIRST_VALUE(B.AGENTNAME)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS AGENTNAME,
        FIRST_VALUE(B.AGENTCODE)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS AGENTCODE,
        FIRST_VALUE(B.BROKERID)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS BROKERID,
        FIRST_VALUE(H.REGION)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS REGION,
        FIRST_VALUE(H.MARKET)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS MARKET,
        FIRST_VALUE(H.LOCATION)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS LOCATION,
        FIRST_VALUE(B.COS_SALES_BDC)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_BDC,
        FIRST_VALUE(B.COS_SALES_BDD)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_BDD,
        FIRST_VALUE(B.COS_SALES_RVP)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_RVP,
        FIRST_VALUE(B.SEGMENTTAGWS)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS SEGMENTTAGWS
    FROM {{ ref('broker_fh_cl_integrate_insurance') }} AS B
    INNER JOIN
        {{ ref('hierarchy_fh_cl_integrate_insurance') }} AS H
        ON B.AGENTCODE = H.AGENTCODE
    WHERE B.AGENTSTATUS = 'Active'
),

REST_OF_BROKER_LIST AS (
    SELECT DISTINCT
        B.USERDEFINED2,
        FIRST_VALUE(B.AGENTNAME)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS AGENTNAME,
        FIRST_VALUE(B.AGENTCODE)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS AGENTCODE,
        FIRST_VALUE(B.BROKERID)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS BROKERID,
        FIRST_VALUE(H.REGION)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS REGION,
        FIRST_VALUE(H.MARKET)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS MARKET,
        FIRST_VALUE(H.LOCATION)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS, B.CREATEDDATE
            )
            AS LOCATION,
        FIRST_VALUE(B.COS_SALES_BDC)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_BDC,
        FIRST_VALUE(B.COS_SALES_BDD)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_BDD,
        FIRST_VALUE(B.COS_SALES_RVP)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS COS_SALES_RVP,
        FIRST_VALUE(B.SEGMENTTAGWS)
            OVER (
                PARTITION BY B.USERDEFINED2
                ORDER BY B.AGENTSTATUS ASC, B.CREATEDDATE DESC
            )
            AS SEGMENTTAGWS
    FROM {{ ref('broker_fh_cl_integrate_insurance') }} AS B
    INNER JOIN
        {{ ref('hierarchy_fh_cl_integrate_insurance') }} AS H
        ON B.AGENTCODE = H.AGENTCODE
    WHERE B.USERDEFINED2 NOT IN (SELECT B.USERDEFINED2 FROM BROKER_ACTIVE AS B)
)

SELECT
    POL_WITH_UD2.*,
    H_COMM.REGION AS FH_COMMISSIONINGAGT_REGION,
    H_COMM.MARKET AS FH_COMMISSIONINGAGT_MARKET,
    H_COMM.LOCATION AS FH_COMMISSIONINGAGT_LOCATION,
    H_COMM.USERDEFINED2 AS FH_COMMISSIONINGAGT_USERDEFINED2,
    H_SERV.REGION AS FH_SERVICINGAGT_REGION,
    H_SERV.MARKET AS FH_SERVICINGAGT_MARKET,
    H_SERV.LOCATION AS FH_SERVICINGAGT_LOCATION,
    H_SERV.USERDEFINED2 AS FH_SERVICINGAGT_USERDEFINED2,
    COALESCE(B_COMM.BROKERID, B_COMM_INACTIVE.BROKERID)
        AS FH_COMMISSIONINGAGT_BROKERID,
    --servicing agent work
    COALESCE(B_COMM.SEGMENTTAGWS, B_COMM_INACTIVE.SEGMENTTAGWS)
        AS FH_COMMISSIONINGAGT_SEGMENTTAGWS,
    COALESCE(B_COMM.COS_SALES_BDC, B_COMM_INACTIVE.COS_SALES_BDC)
        AS FH_COMMISSIONINGAGT_COS_SALES_BDC,
    COALESCE(B_COMM.COS_SALES_BDD, B_COMM_INACTIVE.COS_SALES_BDD)
        AS FH_COMMISSIONINGAGT_COS_SALES_BDD,
    COALESCE(B_COMM.COS_SALES_RVP, B_COMM_INACTIVE.COS_SALES_RVP)
        AS FH_COMMISSIONINGAGT_COS_SALES_RVP,
    COALESCE(B_COMM.AGENTNAME, B_COMM_INACTIVE.AGENTNAME)
        AS FH_COMMISSIONINGAGT_NAME,
    COALESCE(B_SERV.BROKERID, B_SERV_INACTIVE.BROKERID)
        AS FH_SERVICINGAGT_BROKERID,
    COALESCE(B_SERV.SEGMENTTAGWS, B_SERV_INACTIVE.SEGMENTTAGWS)
        AS FH_SERVICINGAGT_SEGMENTTAGWS,
    COALESCE(B_SERV.COS_SALES_BDC, B_SERV_INACTIVE.COS_SALES_BDC)
        AS FH_SERVICINGAGT_COS_SALES_BDC,
    COALESCE(B_SERV.COS_SALES_BDD, B_SERV_INACTIVE.COS_SALES_BDD)
        AS FH_SERVICINGAGT_COS_SALES_BDD,
    COALESCE(B_SERV.COS_SALES_RVP, B_SERV_INACTIVE.COS_SALES_RVP)
        AS FH_SERVICINGAGT_COS_SALES_RVP,
    COALESCE(B_SERV.AGENTNAME, B_SERV_INACTIVE.AGENTNAME)
        AS FH_SERVICINGAGT_NAME

FROM POL_WITH_UD2
LEFT JOIN HIER_W_UD2 H_COMM
    ON POL_WITH_UD2.FH_COMMISSIONINGAGTCODE = H_COMM.AGENTCODE
LEFT JOIN BROKER_ACTIVE AS B_COMM
    ON POL_WITH_UD2.FH_COMMISSIONINGAGT_UD2 = B_COMM.USERDEFINED2
LEFT JOIN REST_OF_BROKER_LIST AS B_COMM_INACTIVE
    ON POL_WITH_UD2.FH_COMMISSIONINGAGT_UD2 = B_COMM_INACTIVE.USERDEFINED2
LEFT JOIN HIER_W_UD2 AS H_SERV
    ON POL_WITH_UD2.FH_SERVICINGAGTCODE = H_SERV.AGENTCODE
LEFT JOIN BROKER_ACTIVE AS B_SERV
    ON POL_WITH_UD2.FH_SERVICINGAGT_UD2 = B_SERV.USERDEFINED2
LEFT JOIN REST_OF_BROKER_LIST AS B_SERV_INACTIVE
    ON POL_WITH_UD2.FH_SERVICINGAGT_UD2 = B_SERV_INACTIVE.USERDEFINED2

