 {{ config(alias='clients', database='report', schema='insurance') }}

SELECT 
INSURANCE_CLIENT_AGENTCODE as "AGENT CODE",
INSURANCE_CLIENT_HOME_PHONE as "HOME PHONE",
INSURANCE_CLIENT_ID as "CLIENT ID",
INSURANCE_CLIENT_LAST_NAME as "LAST NAME",
INSURANCE_CLIENT_MAIN_ADDRESS_ATTN_PREFIX as "MAIN ADDRESS ATTN PREFIX",
INSURANCE_CLIENT_SMOKER_STATUS as "SMOKER STATUS",
INSURANCE_CLIENT_MAIN_ADDRESS_STREET as "MAIN ADDRESS STREET",
INSURANCE_CLIENT_JOINTACCOUNTSTATUS as "JOINT ACCOUNT STATUS",
INSURANCE_CLIENT_EMAIL2 as "EMAIL2",
INSURANCE_CLIENT_COUNTRY_ID as "COUNTRY ID",
INSURANCE_CLIENT_CLIENT_LANGUAGE as "CLIENT LANGUAGE",
INSURANCE_CLIENT_MAIN_ADDRESS_CITY as "MAIN ADDRESS CITY",
INSURANCE_CLIENT_DOB as "DOB",
INSURANCE_CLIENT_MAIN_ADDRESS_STREET2 as "MAIN ADDRESS STREET2",
INSURANCE_CLIENT_MAIN_ADDRESS_STATE_NAME as "MAIN ADDRESS STATE NAME",
INSURANCE_CLIENT_EMAIL as "EMAIL",
INSURANCE_CLIENT_EXTENTION_PHONE as "EXTENTION PHONE",
INSURANCE_CLIENT_FIRST_NAME as "FIRST NAME",
INSURANCE_CLIENT_MAIN_ADDRESS_ZIPCODE as "MAIN ADDRESS ZIPCODE",
INSURANCE_CLIENT_CELL_PHONE as "CELL PHONE",
INSURANCE_CLIENT_AGE_RANGE as "AGE RANGE",
INSURANCE_CLIENT_CODE as "CLIENT CODE",
INSURANCE_CLIENT_GENDER as "GENDER",
INSURANCE_CLIENT_MAIN_ADDRESS_ATTN_LINE as "MAIN ADDRESS ATTN LINE",
INSURANCE_CLIENT_MAIN_ADDRESS_STREET3 as "MAIN ADDRESS STREET3",
INSURANCE_CLIENT_OTHER_PHONE as "OTHER PHONE",
INSURANCE_CLIENT_WORK_PHONE as "WORK PHONE"

from {{ ref ('clients_analyze_insurance')  }}