 {{  config(alias='policy', database='report', schema='insurance')  }} 
 

SELECT 
PLANNAME as "PLAN NAME",
SENTTOICDATE as "SENT TO IC DATE",
MAILEDDATE as "MAILED DATE",
APPSOURCE as "APP SOURCE",
COMMPREMIUMAMOUNT as "COMM PREMIUM AMOUNT",
FIRSTOWNERCLIENTCODE as "FIRST OWNER CLIENT CODE",
ISSUEPROVINCE as "ISSUE PROVINCE",
SETTLEMENTDATE as "SETTLEMENT DATE",
LASTCOMMISSIONPROCESSDATE as "LAST COMMISSION PROCESS DATE",
PREMIUMAMOUNT as "PREMIUM AMOUNT",
SUMINSURED as "SUMINSURED",
APPTYPE as "APP TYPE",
GROSSAMOUNT as "GROSS AMOUNT",
MGAFYOAMOUNT as "MGA FYO AMOUNT",
RENEWALDATE as "RENEWAL DATE",
CARRIER as "CARRIER",
CONTRACTDATE as "CONTRACT DATE",
FACEAMOUNT as "FACE AMOUNT",
CONVERSIONEXPIRYDATE as "CONVERSION EXPIRY DATE",
APPLICATIONDATE as "APPLICATION DATE",
CREATEDBY as "CREATED BY",
CREATEDDATE as "CREATE DDATE",
EXPIRYDATE as "EXPIR YDATE",
ANNUALPREMIUMAMOUNT as "ANNUAL PREMIUM AMOUNT",
FIRSTINSUREDCLIENTCODE as "FIRST INSURED CLIENT CODE",
PLANTYPE as "PLANTYPE",
POLICYNUMBER as "POLICY NUMBER",
POLICY_CLIENTCODE as "POLICY CLIENT CODE",
STATUS as "STATUS",
PLANID as "PLANID",
POLICYCODE as "POLICY CODE",
BENEFICIARIES as "BENEFICIARIES"

from {{ ref ('policy_analyze_insurance')  }}