{{			
    config (			
        materialized="view",			
        alias='policy_itm_fh', 			
        database='report', 			
        schema='insurance'			
    )			
}}	

WITH MOST AS (
    SELECT
        POL.*,
        ITM.ITM_END_DATE AS FH_ITM_END_DATE,
        ITM.ITM AS FH_ITM,
        ITM.DAYS_IN_STATUS AS FH_DAYS_IN_STATUS
    FROM
        {{ ref('policy_fh_report_insurance') }} POL
        LEFT JOIN {{ ref('itm_calcs_FH_report_insurance') }} ITM ON POL.POLICYCODE = ITM.POLICYCODE
        AND POL.FH_SERVICINGAGTCODE = ITM.FH_SERVICINGAGTCODE
        AND POL.POLICYNUMBER = ITM.POLICYNUMBER
    GROUP BY
        1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,
        28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54
      
)
SELECT
    MOST.FH_POLICYCATEGORY,
    MOST.POLICYCODE,
    MOST.POLICYGROUPCODE,
    MOST.FH_SERVICINGAGTCODE,
    MOST.FH_SERVICINGAGTSPLIT,
    MOST.FH_COMMISSIONINGAGTCODE,
    MOST.FH_COMMISSIONINGAGTSPLIT,
    MOST.FH_CARRIERENG,
    MOST.FH_CARRIERFR,
    MOST.POLICYNUMBER,
    MOST.PLANID,
    MOST.FH_PLANTYPE,
    MOST.FH_PLANNAMEENG,
    MOST.FH_PLANNAMEFR,
    MOST.PREMIUMAMOUNT,
    MOST.ANNUALPREMIUMAMOUNT,
    MOST.COMMPREMIUMAMOUNT,
    MOST.PAYMENTMODE,
    MOST.FACEAMOUNT,
    MOST.CREATEDBY,
    MOST.CREATEDDATE,
    MOST.CONTRACTDATE,
    MOST.SETTLEMENTDATE,
    MOST.EXPIRYDATE,
    MOST.RENEWALDATE,
    MOST.SENTTOICDATE,
    MOST.MAILEDDATE,
    MOST.FH_FINPOSTDATE,
    MOST.FH_STATUSCODE,
    MOST.FH_STATUSNAMEENG,
    MOST.FH_STATUSNAMEFR,
    MOST.FH_STATUSCATEGORY,
    MOST.APPCOUNT,
    MOST.FH_FYCSERVAMT,
    MOST.FH_FYCCOMMAMT,
    MOST.MGAFYOAMOUNT,
    MOST.ISSUEPROVINCE,
    MOST.FH_APPSOURCE,
    MOST.FH_APPTYPE,
    MOST.LASTCOMMISSIONPROCESSDATE,
    MOST.FIRSTOWNERCLIENTCODE,
    MOST.FIRSTINSUREDCLIENTCODE,
    MOST.ISMAINCOVERAGE,
    MOST.FH_SETTLEMENTDATE,
    MOST.FH_STARTDATE,
    MOST.FH_PREMIUM,
    MOST.FH_PREM_COMMWGT,
    MOST.FH_PREM_SERVWGT,
    MOST.APPLICATIONDATE,
    MOST.FH_PLACEDDATE,
    MOST.FH_FYCPLACED,
    COALESCE(MOST.FH_ITM_END_DATE, ITM.ITM_END_DATE) AS FH_ITM_END_DATE,
    COALESCE(MOST.FH_ITM, ITM.ITM) AS FH_ITM,
    COALESCE(MOST.FH_DAYS_IN_STATUS, ITM.DAYS_IN_STATUS) AS FH_DAYS_IN_STATUS
FROM
    MOST
    LEFT JOIN {{ ref('itm_calcs_FH_report_insurance') }} ITM ON MOST.POLICYCODE = ITM.POLICYCODE
    AND MOST.FH_SERVICINGAGTCODE = ITM.FH_SERVICINGAGTCODE
GROUP BY
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,
    28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54