{{  config(alias='__comm_agt_mapped', database='normalize', schema='insurance', tags=["policy_fh"])  }}

WITH FHFORMAT AS (
        SELECT
            *
        FROM
            {{ ref('__FHFORMAT_insurance') }} --normalize.prod_insurance.__FHFORMAT
    ),
    CORRECTED_AGT_SPLITS AS (
        SELECT
            *
        FROM
            {{ ref('__COMM_WGTS_insurance') }} --SANDBOX.EVELYN.__COMM_WGTS --normalize.prod_insurance.__comm_wgts
    ),
    S1_SERV_AGT_WT_APPEARS_2X AS (
        SELECT
            FHFORMAT.POLICYCODE,
            FH_SERVICINGAGTSPLIT,
            COUNT(*) AS COUNT_OF_SPLIT,
        FROM
            FHFORMAT
        GROUP BY
            1, 2
        HAVING
            COUNT_OF_SPLIT = 2
    ),
    S2_SERV_AGT_WT_APPEARS_2X AS (
        SELECT
            FHFORMAT.POLICYCODE,
            FH_SERVICINGAGTCODE,
            S1_SERV_AGT_WT_APPEARS_2X.FH_SERVICINGAGTSPLIT,
            ROW_NUMBER() OVER (
                PARTITION BY FHFORMAT.POLICYCODE,
                FHFORMAT.FH_SERVICINGAGTSPLIT
                ORDER BY
                    FHFORMAT.POLICYCODE,
                    FHFORMAT.FH_SERVICINGAGTSPLIT ASC
            ) AS TEMP_RANK
        FROM
            FHFORMAT
            LEFT JOIN S1_SERV_AGT_WT_APPEARS_2X ON S1_SERV_AGT_WT_APPEARS_2X.POLICYCODE = FHFORMAT.POLICYCODE
            AND S1_SERV_AGT_WT_APPEARS_2X.FH_SERVICINGAGTSPLIT = FHFORMAT.FH_SERVICINGAGTSPLIT
    ),
    S3_SERV_AGT_WT_APPEARS_2X AS (
        SELECT
            F.POLICYCODE,
            OWNERCODE AS COMMISSIONINGAGTCODE,
            CORR_PD_AGT_SPLIT AS COMMISSIONINGAGTSPLIT,
            ROW_NUMBER() OVER (
                PARTITION BY F.POLICYCODE,
                F.CORR_PD_AGT_SPLIT
                ORDER BY
                    F.POLICYCODE,
                    F.CORR_PD_AGT_SPLIT ASC
            ) AS FIN_RANK,
            max(F.PAID) AS COMM_FYC_PAID --changed from sum to max.
        FROM
            CORRECTED_AGT_SPLITS F
            JOIN S2_SERV_AGT_WT_APPEARS_2X P ON F.POLICYCODE = P.POLICYCODE
            AND F.CORR_PD_AGT_SPLIT = P.FH_SERVICINGAGTSPLIT
        WHERE
            F.POLICYCODE IN (
                SELECT
                    DISTINCT POLICYCODE
                FROM
                    S1_SERV_AGT_WT_APPEARS_2X
            )
        GROUP BY
            1, 2, 3
    ),
    S4_SERV_AGT_WT_APPEARS_2X_JOINED AS (
        SELECT
            POLDATA.POLICYCODE,
            POLDATA.FH_SERVICINGAGTCODE,
            POLDATA.FH_SERVICINGAGTSPLIT,
            FINDATA.COMMISSIONINGAGTCODE,
            FINDATA.COMMISSIONINGAGTSPLIT,
            FINDATA.COMM_FYC_PAID
        FROM
            S2_SERV_AGT_WT_APPEARS_2X POLDATA
            JOIN S3_SERV_AGT_WT_APPEARS_2X FINDATA ON POLDATA.POLICYCODE = FINDATA.POLICYCODE
            AND POLDATA.TEMP_RANK = FINDATA.FIN_RANK
    ),
    S1_SERV_AGT_WT_APPEARS_1X AS (
        SELECT
            FHFORMAT.POLICYCODE,
            FH_SERVICINGAGTSPLIT,
            COUNT(*) AS COUNT_OF_SPLIT,
            SUM(FYCAMOUNT) AS FYCAMOUNT --this is for servicing only.
        FROM
            FHFORMAT
        GROUP BY
            1, 2
        HAVING
            COUNT_OF_SPLIT = 1
    ),
    S2_SERV_AGT_WT_APPEARS_1X AS (
        SELECT
            S.POLICYCODE,
            OWNERCODE AS COMMISSIONINGAGTCODE,
            CORR_PD_AGT_SPLIT AS COMMISSIONINGAGTSPLIT,
            PAID,
            ROW_NUMBER() OVER (
                PARTITION BY S.POLICYCODE,
                OWNERCODE
                ORDER BY
                    S.POLICYCODE,
                    OWNERCODE ASC
            ) AS FIN_RANK,
            S.PAID AS FYC_COMM_AMT
        FROM
            CORRECTED_AGT_SPLITS S
        WHERE
            S.POLICYCODE IN (
                SELECT
                    DISTINCT POLICYCODE
                FROM
                    S1_SERV_AGT_WT_APPEARS_1X
            )
    ),
    S2A_CASES_WHERE_NUM_AGTS_NOTEQ AS (
        SELECT
            A.POLICYCODE,
            COUNT(DISTINCT FH_SERVICINGAGTCODE) SERV_AGT_COUNT,
            COUNT(DISTINCT COMMISSIONINGAGTCODE) COMM_AGT_COUNT
        FROM
            FHFORMAT A
            JOIN S2_SERV_AGT_WT_APPEARS_1X B ON A.POLICYCODE = B.POLICYCODE
        GROUP BY
            1
        HAVING
            COUNT(DISTINCT FH_SERVICINGAGTCODE) = 1
            AND COUNT(DISTINCT COMMISSIONINGAGTCODE) in (2, 3)
    ),
    S3_SERV_AGT_WT_APPEARS_1X_JOINED AS (
        SELECT
            POLDATA.POLICYCODE,
            POLDATA.FH_SERVICINGAGTSPLIT,
            FINDATA.COMMISSIONINGAGTCODE,
            FINDATA.COMMISSIONINGAGTSPLIT,
            FINDATA.PAID AS FYC_COMM_AMT
        FROM
            S1_SERV_AGT_WT_APPEARS_1X POLDATA
            JOIN S2_SERV_AGT_WT_APPEARS_1X FINDATA ON POLDATA.POLICYCODE = FINDATA.POLICYCODE
            AND POLDATA.FH_SERVICINGAGTSPLIT = FINDATA.COMMISSIONINGAGTSPLIT
        WHERE
            POLDATA.POLICYCODE NOT IN (
                SELECT
                    DISTINCT POLICYCODE
                FROM
                    S2A_CASES_WHERE_NUM_AGTS_NOTEQ
            )
    ),
    RANKED AS (
        SELECT
            A.*,
            C.FH_SERVICINGAGTSPLIT,
            ROW_NUMBER() OVER (
                PARTITION BY A.POLICYCODE
                ORDER BY
                    A.POLICYCODE ASC
            ) AS TEMP_RANK,
        FROM
            S2_SERV_AGT_WT_APPEARS_1X A
            JOIN S2A_CASES_WHERE_NUM_AGTS_NOTEQ B on A.POLICYCODE = B.POLICYCODE
            JOIN S1_SERV_AGT_WT_APPEARS_1X C on C.POLICYCODE = A.POLICYCODE
    ),
    RANKED_w_SERV_AGT_CODE AS (
        SELECT
            R.POLICYCODE,
            R.COMMISSIONINGAGTCODE,
            R.COMMISSIONINGAGTSPLIT,
            R.PAID,
            R.FIN_RANK,
            FH_SERVICINGAGTCODE,
            R.FH_SERVICINGAGTSPLIT,
            P.APPCOUNT,
            P.FYCAMOUNT,
            TEMP_RANK
        FROM
            RANKED R
            LEFT JOIN FHFORMAT P on R.POLICYCODE = P.POLICYCODE
    ),
    S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U1 AS (
        SELECT
            POLICYCODE,
            FH_SERVICINGAGTCODE,
            FH_SERVICINGAGTSPLIT,
            COMMISSIONINGAGTCODE,
            COMMISSIONINGAGTSPLIT,
            APPCOUNT,
            FYCAMOUNT,
            PAID AS FYCCOMMAMT
        FROM
            RANKED_w_SERV_AGT_CODE
        WHERE
            TEMP_RANK = 1
    ),
    S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U2 AS (
        SELECT
            POLICYCODE,
            FH_SERVICINGAGTCODE,
            0 as FH_SERVICINGAGTSPLIT,
            COMMISSIONINGAGTCODE,
            COMMISSIONINGAGTSPLIT,
            0 AS APPCOUNT,
            0 AS FYCAMOUNT,
            PAID AS FYCCOMMAMT
        FROM
            RANKED_w_SERV_AGT_CODE
        WHERE
            TEMP_RANK = 2
    ),
    S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U3 AS (
        SELECT
            POLICYCODE,
            FH_SERVICINGAGTCODE,
            0 as FH_SERVICINGAGTSPLIT,
            COMMISSIONINGAGTCODE,
            COMMISSIONINGAGTSPLIT,
            0 AS APPCOUNT,
            0 AS FYCAMOUNT,
            PAID AS FYCCOMMAMT
        FROM
            RANKED_w_SERV_AGT_CODE
        WHERE
            TEMP_RANK = 3
    ),
    S5_ONE_SERVAGT_MANY_COMM AS (
        SELECT
            *
        FROM
            S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U1
        UNION
        SELECT
            *
        FROM
            S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U2
        UNION
        SELECT
            *
        FROM
            S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U3
    )
    SELECT
        FH_POLICYCATEGORY,
        FHFORMAT.POLICYCODE,
        POLICYGROUPCODE,
        FHFORMAT.FH_SERVICINGAGTCODE,
        FHFORMAT.FH_SERVICINGAGTSPLIT,
        COALESCE(
            TWO.COMMISSIONINGAGTCODE,
            ONE.COMMISSIONINGAGTCODE
        ) AS FH_COMMISSIONINGAGTCODE,
        COALESCE(
            TWO.COMMISSIONINGAGTSPLIT,
            ONE.COMMISSIONINGAGTSPLIT
        ) AS FH_COMMISSIONINGAGTSPLIT,
        FH_CARRIERENG,
        FH_CARRIERFR,
        POLICYNUMBER,
        PLANID,
        FH_PLANTYPE,
        FH_PLANNAMEENG,
        FH_PLANNAMEFR,
        PREMIUMAMOUNT,
        ANNUALPREMIUMAMOUNT,
        COMMPREMIUMAMOUNT,
        PAYMENTMODE,
        FACEAMOUNT,
        CREATEDBY,
        CREATEDDATE,
        APPLICATIONDATE,
        CONTRACTDATE,
        SETTLEMENTDATE,
        EXPIRYDATE,
        RENEWALDATE,
        SENTTOICDATE,
        MAILEDDATE,
        FH_FINPOSTDATE,
        FH_STATUSCODE,
        FH_STATUSNAMEENG,
        FH_STATUSNAMEFR,
        FH_STATUSCATEGORY,
        APPCOUNT,
        FYCAMOUNT AS FH_FYCSERVAMT,
        COALESCE(TWO.COMM_FYC_PAID, ONE.FYC_COMM_AMT, 0) AS FH_FYCCOMMAMT,
        MGAFYOAMOUNT,
        ISSUEPROVINCE,
        FH_APPSOURCE,
        FH_APPTYPE,
        LASTCOMMISSIONPROCESSDATE,
        FIRSTOWNERCLIENTCODE,
        FIRSTINSUREDCLIENTCODE,
        ISMAINCOVERAGE,
        FH_SETTLEMENTDATE,
        FH_STARTDATE,
        FH_PREMIUM
    FROM
        FHFORMAT
        LEFT JOIN S4_SERV_AGT_WT_APPEARS_2X_JOINED TWO ON TWO.POLICYCODE = FHFORMAT.POLICYCODE
        AND TWO.FH_SERVICINGAGTSPLIT = FHFORMAT.FH_SERVICINGAGTSPLIT
        AND TWO.FH_SERVICINGAGTCODE = FHFORMAT.FH_SERVICINGAGTCODE
        LEFT JOIN S3_SERV_AGT_WT_APPEARS_1X_JOINED ONE ON ONE.POLICYCODE = FHFORMAT.POLICYCODE
        AND ONE.FH_SERVICINGAGTSPLIT = FHFORMAT.FH_SERVICINGAGTSPLIT
    WHERE
        FHFORMAT.POLICYCODE NOT IN (
            SELECT
                DISTINCT POLICYCODE
            FROM
                S2A_CASES_WHERE_NUM_AGTS_NOTEQ
        )
    GROUP BY
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47
    UNION
    SELECT
        P.FH_POLICYCATEGORY,
        P.POLICYCODE,
        P.POLICYGROUPCODE,
        P.FH_SERVICINGAGTCODE,
        A.FH_SERVICINGAGTSPLIT,
        A.COMMISSIONINGAGTCODE AS FH_COMMISSIONINGAGTCODE,
        A.COMMISSIONINGAGTSPLIT AS FH_COMMISSIONINGAGTSPLIT,
        P.FH_CARRIERENG,
        P.FH_CARRIERFR,
        P.POLICYNUMBER,
        P.PLANID,
        P.FH_PLANTYPE,
        P.FH_PLANNAMEENG,
        P.FH_PLANNAMEFR,
        P.PREMIUMAMOUNT,
        P.ANNUALPREMIUMAMOUNT,
        P.COMMPREMIUMAMOUNT,
        P.PAYMENTMODE,
        P.FACEAMOUNT,
        P.CREATEDBY,
        P.CREATEDDATE,
        P.APPLICATIONDATE,
        P.CONTRACTDATE,
        P.SETTLEMENTDATE,
        P.EXPIRYDATE,
        P.RENEWALDATE,
        P.SENTTOICDATE,
        P.MAILEDDATE,
        P.FH_FINPOSTDATE,
        P.FH_STATUSCODE,
        P.FH_STATUSNAMEENG,
        P.FH_STATUSNAMEFR,
        P.FH_STATUSCATEGORY,
        A.APPCOUNT,
        A.FYCAMOUNT AS FH_FYCSERVAMT,
        A.FYCCOMMAMT AS FH_FYCCOMMAMT,
        P.MGAFYOAMOUNT,
        P.ISSUEPROVINCE,
        P.FH_APPSOURCE,
        P.FH_APPTYPE,
        P.LASTCOMMISSIONPROCESSDATE,
        P.FIRSTOWNERCLIENTCODE,
        P.FIRSTINSUREDCLIENTCODE,
        P.ISMAINCOVERAGE,
        P.FH_SETTLEMENTDATE,
        P.FH_STARTDATE,
        P.FH_PREMIUM
    FROM
        S5_ONE_SERVAGT_MANY_COMM A
        LEFT JOIN FHFORMAT P ON A.POLICYCODE = P.POLICYCODE
        AND A.FH_SERVICINGAGTCODE = P.FH_SERVICINGAGTCODE
    GROUP BY
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47