{{  config(alias='__comm_agt_mapped', database='normalize', schema='insurance')  }}

WITH 

FHFORMAT AS
(SELECT * FROM {{ ref ('__FHFORMAT_insurance') }}),

CORRECTED_AGT_SPLITS AS
(SELECT * FROM {{ ref ('__COMM_WGTS_insurance') }}),

S1_SERV_AGT_WT_APPEARS_2X AS
(SELECT
FHFORMAT.POLICYCODE,
SERVICINGAGTSPLIT,
COUNT(*) AS COUNT_OF_SPLIT,
FROM FHFORMAT
GROUP BY 1,2
HAVING COUNT_OF_SPLIT=2
),

S2_SERV_AGT_WT_APPEARS_2X AS
(SELECT
FHFORMAT.POLICYCODE,
SERVICINGAGTCODE,
S1_SERV_AGT_WT_APPEARS_2X.SERVICINGAGTSPLIT,
ROW_NUMBER() OVER (PARTITION BY FHFORMAT.POLICYCODE, FHFORMAT.SERVICINGAGTSPLIT ORDER BY FHFORMAT.POLICYCODE, FHFORMAT.SERVICINGAGTSPLIT ASC) AS TEMP_RANK
FROM FHFORMAT 
LEFT JOIN S1_SERV_AGT_WT_APPEARS_2X ON S1_SERV_AGT_WT_APPEARS_2X.POLICYCODE = FHFORMAT.POLICYCODE AND S1_SERV_AGT_WT_APPEARS_2X.SERVICINGAGTSPLIT = FHFORMAT.SERVICINGAGTSPLIT
),

S3_SERV_AGT_WT_APPEARS_2X AS
(SELECT
F.POLICYCODE,
OWNERCODE AS COMMISSIONINGAGTCODE,
CORR_PD_AGT_SPLIT AS COMMISSIONINGAGTSPLIT,
ROW_NUMBER() OVER (PARTITION BY F.POLICYCODE,F.CORR_PD_AGT_SPLIT ORDER BY F.POLICYCODE, F.CORR_PD_AGT_SPLIT ASC) AS FIN_RANK
FROM CORRECTED_AGT_SPLITS F JOIN S2_SERV_AGT_WT_APPEARS_2X P ON F.POLICYCODE = P.POLICYCODE AND F.CORR_PD_AGT_SPLIT = P.SERVICINGAGTSPLIT
WHERE F.POLICYCODE IN (SELECT DISTINCT POLICYCODE FROM S1_SERV_AGT_WT_APPEARS_2X)
GROUP BY 1,2,3
),

S4_SERV_AGT_WT_APPEARS_2X_JOINED AS
(SELECT
POLDATA.POLICYCODE,
POLDATA.SERVICINGAGTCODE,
POLDATA.SERVICINGAGTSPLIT,
FINDATA.COMMISSIONINGAGTCODE,
FINDATA.COMMISSIONINGAGTSPLIT
FROM S2_SERV_AGT_WT_APPEARS_2X POLDATA 
JOIN S3_SERV_AGT_WT_APPEARS_2X FINDATA ON POLDATA.POLICYCODE = FINDATA.POLICYCODE AND POLDATA.TEMP_RANK = FINDATA.FIN_RANK
),

S1_SERV_AGT_WT_APPEARS_1X AS
(SELECT
FHFORMAT.POLICYCODE,
SERVICINGAGTSPLIT,
COUNT(*) AS COUNT_OF_SPLIT,
SUM(FYCAMOUNT) AS FYCAMOUNT
FROM FHFORMAT
GROUP BY 1,2
HAVING COUNT_OF_SPLIT=1
),

S2_SERV_AGT_WT_APPEARS_1X AS
(SELECT
S.POLICYCODE,
OWNERCODE AS COMMISSIONINGAGTCODE,
CORR_PD_AGT_SPLIT AS COMMISSIONINGAGTSPLIT,
PAID,
ROW_NUMBER() OVER (PARTITION BY S.POLICYCODE, OWNERCODE ORDER BY S.POLICYCODE, OWNERCODE ASC) AS FIN_RANK
FROM CORRECTED_AGT_SPLITS S
WHERE S.POLICYCODE IN (SELECT DISTINCT POLICYCODE FROM S1_SERV_AGT_WT_APPEARS_1X)
),

S2A_CASES_WHERE_NUM_AGTS_NOTEQ AS
(SELECT a.POLICYCODE, COUNT(DISTINCT SERVICINGAGTCODE) serv_agt_count, count(distinct COMMISSIONINGAGTCODE) comm_agt_count
FROM FHFORMAT a join S2_SERV_AGT_WT_APPEARS_1X b ON a.POLICYCODE = b.POLICYCODE
GROUP BY 1
HAVING COUNT(DISTINCT SERVICINGAGTCODE) = 1 AND COUNT(DISTINCT COMMISSIONINGAGTCODE) in (2,3)),

S3_SERV_AGT_WT_APPEARS_1X_JOINED AS
(SELECT
POLDATA.POLICYCODE,
POLDATA.SERVICINGAGTSPLIT,
FINDATA.COMMISSIONINGAGTCODE,
FINDATA.COMMISSIONINGAGTSPLIT,
POLDATA.FYCAMOUNT AS FYC_COMM_AMT
FROM S1_SERV_AGT_WT_APPEARS_1X POLDATA 
JOIN S2_SERV_AGT_WT_APPEARS_1X FINDATA ON POLDATA.POLICYCODE = FINDATA.POLICYCODE AND POLDATA.SERVICINGAGTSPLIT = FINDATA.COMMISSIONINGAGTSPLIT
WHERE POLDATA.POLICYCODE NOT IN (SELECT DISTINCT POLICYCODE FROM S2A_CASES_WHERE_NUM_AGTS_NOTEQ)
),
 
RANKED AS
(SELECT a.* , 
c.SERVICINGAGTSPLIT,
ROW_NUMBER() OVER (PARTITION BY a.POLICYCODE ORDER BY a.POLICYCODE ASC) AS TEMP_RANK,
FROM S2_SERV_AGT_WT_APPEARS_1X a 
JOIN S2A_CASES_WHERE_NUM_AGTS_NOTEQ b on a.policycode = b.policycode
JOIN S1_SERV_AGT_WT_APPEARS_1X c on c.policycode = a.policycode),

RANKED_w_SERV_AGT_CODE AS
(SELECT
R.POLICYCODE,
R.COMMISSIONINGAGTCODE,
R.COMMISSIONINGAGTSPLIT,
R.PAID,
R.FIN_RANK,
SERVICINGAGTCODE,
R.SERVICINGAGTSPLIT,
P.APPCOUNT,
P.FYCAMOUNT,
TEMP_RANK
FROM RANKED R LEFT JOIN FHFORMAT P on R.POLICYCODE = P.POLICYCODE
),

S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U1 AS 
(SELECT POLICYCODE, SERVICINGAGTCODE, 
SERVICINGAGTSPLIT, COMMISSIONINGAGTCODE, COMMISSIONINGAGTSPLIT, APPCOUNT, FYCAMOUNT, PAID AS FYCCOMMAMT
FROM RANKED_w_SERV_AGT_CODE 
WHERE TEMP_RANK = 1),

S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U2 AS 
(SELECT POLICYCODE, SERVICINGAGTCODE, 
0 as SERVICINGAGTSPLIT, COMMISSIONINGAGTCODE, COMMISSIONINGAGTSPLIT, 
0 AS APPCOUNT,
0 AS FYCAMOUNT,
PAID AS FYCCOMMAMT
FROM RANKED_w_SERV_AGT_CODE
WHERE TEMP_RANK = 2 ),

S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U3 AS 
(SELECT POLICYCODE, SERVICINGAGTCODE, 0 as SERVICINGAGTSPLIT, COMMISSIONINGAGTCODE, COMMISSIONINGAGTSPLIT, 
0 AS APPCOUNT,
0 AS FYCAMOUNT,
PAID AS FYCCOMMAMT
FROM RANKED_w_SERV_AGT_CODE
WHERE TEMP_RANK = 3 ),

S5_ONE_SERVAGT_MANY_COMM AS
(SELECT * FROM S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U1
UNION
SELECT * FROM S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U2
UNION
SELECT * FROM S4A_ONE_SERVAGT_TWOTHREE_COMMAGT_U3
)

SELECT
POLICYCATEGORY,
FHFORMAT.POLICYCODE,
POLICYGROUPCODE,
FHFORMAT.SERVICINGAGTCODE,
FHFORMAT.SERVICINGAGTSPLIT,
COALESCE( TWO.COMMISSIONINGAGTCODE ,ONE.COMMISSIONINGAGTCODE) AS COMMISSIONINGAGTCODE,
COALESCE( TWO.COMMISSIONINGAGTSPLIT ,ONE.COMMISSIONINGAGTSPLIT) AS COMMISSIONINGAGTSPLIT,
CARRIERENG,
CARRIERFR,
POLICYNUMBER,
PLANID,
PLANTYPE,
PLANNAMEENG,
PLANNAMEFR,
PREMIUMAMOUNT,
ANNUALPREMIUMAMOUNT,
COMMPREMIUMAMOUNT,
PAYMENTMODE,
FACEAMOUNT,
CREATEDBY,
CREATEDDATE,
APPLICATIONDATE,
CONTRACTDATE,
SETTLEMENTDATE,
EXPIRYDATE,
RENEWALDATE,
SENTTOICDATE,
MAILEDDATE,
FINPOSTDATE,
STATUSCODE,
STATUSNAMEENG,
STATUSNAMEFR,
STATUSCATEGORY,
APPCOUNT,
FYCAMOUNT AS FYCSERVAMT,
FYCAMOUNT AS FYCCOMMAMT,
MGAFYOAMOUNT,
ISSUEPROVINCE,
APPSOURCE,
APPTYPE,
LASTCOMMISSIONPROCESSDATE,
FIRSTOWNERCLIENTCODE,
FIRSTINSUREDCLIENTCODE,
ISMAINCOVERAGE,
FH_SETTLEMENTDATE,
FH_STARTDATE,
FH_PREMIUM
FROM FHFORMAT
LEFT JOIN S4_SERV_AGT_WT_APPEARS_2X_JOINED TWO 
ON TWO.POLICYCODE = FHFORMAT.POLICYCODE AND TWO.SERVICINGAGTSPLIT = FHFORMAT.SERVICINGAGTSPLIT AND TWO.SERVICINGAGTCODE = FHFORMAT.SERVICINGAGTCODE
LEFT JOIN S3_SERV_AGT_WT_APPEARS_1X_JOINED ONE ON ONE.POLICYCODE = FHFORMAT.POLICYCODE AND ONE.SERVICINGAGTSPLIT = FHFORMAT.SERVICINGAGTSPLIT
WHERE FHFORMAT.POLICYCODE NOT IN (SELECT DISTINCT policycode from S2A_CASES_WHERE_NUM_AGTS_NOTEQ)  
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47

UNION

SELECT
P.POLICYCATEGORY,
P.POLICYCODE,
P.POLICYGROUPCODE,
P.SERVICINGAGTCODE,
A.SERVICINGAGTSPLIT,
A.COMMISSIONINGAGTCODE,
A.COMMISSIONINGAGTSPLIT,
P.CARRIERENG,
P.CARRIERFR,
P.POLICYNUMBER,
P.PLANID,
P.PLANTYPE,
P.PLANNAMEENG,
P.PLANNAMEFR,
P.PREMIUMAMOUNT,
P.ANNUALPREMIUMAMOUNT,
P.COMMPREMIUMAMOUNT,
P.PAYMENTMODE,
P.FACEAMOUNT,
P.CREATEDBY,
P.CREATEDDATE,
P.APPLICATIONDATE,
P.CONTRACTDATE,
P.SETTLEMENTDATE,
P.EXPIRYDATE,
P.RENEWALDATE,
P.SENTTOICDATE,
P.MAILEDDATE,
P.FINPOSTDATE,
P.STATUSCODE,
P.STATUSNAMEENG,
P.STATUSNAMEFR,
P.STATUSCATEGORY,
A.APPCOUNT,
A.FYCAMOUNT AS FYCSERVAMT,
A.FYCCOMMAMT AS FYCCOMMAMT,
P.MGAFYOAMOUNT,
P.ISSUEPROVINCE,
P.APPSOURCE,
P.APPTYPE,
P.LASTCOMMISSIONPROCESSDATE,
P.FIRSTOWNERCLIENTCODE,
P.FIRSTINSUREDCLIENTCODE,
P.ISMAINCOVERAGE,
P.FH_SETTLEMENTDATE,
P.FH_STARTDATE,
P.FH_PREMIUM
FROM S5_ONE_SERVAGT_MANY_COMM A LEFT JOIN FHFORMAT P
ON A.POLICYCODE = P.POLICYCODE AND A.SERVICINGAGTCODE = P.SERVICINGAGTCODE
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47