{{ config(alias='__freeze_settlement', database='normalize', schema='insurance', tags=["policy_fh"]) }}

WITH
REMOVE_DEFAULT_DT AS (
    SELECT * FROM
        {{ ref('settlementdate') }}
    WHERE  YEAR(SETTLEMENTDATE) > 1920 and SETTLEMENTDATE is not null
),

POL_FH_DISTINCT_ONLY AS (
    SELECT DISTINCT
        POLICYCODE,
        POLICYNUMBER
    FROM {{ ref('__fix_two_serv_one_comm_normalize_insurance') }}

    INTERSECT

    SELECT DISTINCT
        POLICYCODE,
        POLICYNUMBER
    FROM {{ ref('settlementdate') }}
    WHERE SETTLEMENTDATE is not null
),

EARLIEST_DATE AS (
    SELECT
        REMOVE_DEFAULT_DT.POLICYCODE,
        POLICYGROUPCODE,
        REMOVE_DEFAULT_DT.POLICYNUMBER,
        MIN(SETTLEMENTDATE) AS SETTLEMENTDATE
    FROM REMOVE_DEFAULT_DT
    INNER JOIN
        POL_FH_DISTINCT_ONLY
        ON
            REMOVE_DEFAULT_DT.POLICYCODE = POL_FH_DISTINCT_ONLY.POLICYCODE
            AND REMOVE_DEFAULT_DT.POLICYNUMBER
            = POL_FH_DISTINCT_ONLY.POLICYNUMBER
    GROUP BY 1, 2, 3
)

SELECT
    FH_POLICYCATEGORY,
    POL.POLICYCODE,
    POL.POLICYGROUPCODE,
    FH_SERVICINGAGTCODE,
    FH_SERVICINGAGTSPLIT,
    FH_COMMISSIONINGAGTCODE,
    FH_COMMISSIONINGAGTSPLIT,
    FH_CARRIERENG,
    FH_CARRIERFR,
    POL.POLICYNUMBER,
    PLANID,
    FH_PLANTYPE,
    FH_PLANNAMEENG,
    FH_PLANNAMEFR,
    PREMIUMAMOUNT,
    ANNUALPREMIUMAMOUNT,
    COMMPREMIUMAMOUNT,
    PAYMENTMODE,
    FACEAMOUNT,
    CREATEDBY,
    CREATEDDATE,
    CONTRACTDATE,
    A.SETTLEMENTDATE,
    EXPIRYDATE,
    RENEWALDATE,
    SENTTOICDATE,
    MAILEDDATE,
    FH_FINPOSTDATE,
    FH_STATUSCODE,
    FH_STATUSNAMEENG,
    FH_STATUSNAMEFR,
    FH_STATUSCATEGORY,
    APPCOUNT,
    FH_FYCSERVAMT,
    FH_FYCCOMMAMT,
    MGAFYOAMOUNT,
    ISSUEPROVINCE,
    FH_APPSOURCE,
    FH_APPTYPE,
    LASTCOMMISSIONPROCESSDATE,
    FIRSTOWNERCLIENTCODE,
    FIRSTINSUREDCLIENTCODE,
    ISMAINCOVERAGE,
    FH_SETTLEMENTDATE,
    FH_STARTDATE,
    FH_PREMIUM,
    FH_PREM_COMMWGT,
    FH_PREM_SERVWGT,
    APPLICATIONDATE,
    COALESCE(A.SETTLEMENTDATE, FH_FINPOSTDATE) AS FH_PLACEDDATE,
    COALESCE(FH_FYCCOMMAMT, FH_FYCSERVAMT,0) AS FH_FYCPLACED
FROM {{ ref('__fix_two_serv_one_comm_normalize_insurance') }} AS POL
LEFT JOIN EARLIEST_DATE AS A
    ON POL.POLICYCODE = A.POLICYCODE
    
   
