{{			
    config (			
        materialized="view",			
        alias='hierarchy', 			
        database='normalize', 			
        schema='insurance'			
    )			
}}	

WITH H1 AS (
SELECT
    DEPTH, 
    CONCAT('^',PARENTNODEID,'^')::VARCHAR AS PARENTNODEID,  
    CONCAT('^',NODEID,'^')::VARCHAR AS BRANCHID, 
    CASE 
	    WHEN 
            CHARINDEX('Branch Brokers', NODENAME) > 0 AND
            (NODENAME LIKE ('%Branch Brokers%') OR NODENAME LIKE ('%DEPT%'))
            AND	NODENAME NOT LIKE ('%DIVISION%')
            AND NODENAME NOT LIKE ('%MAP%')
        THEN UPPER(REPLACE(NODENAME, 'Branch Brokers', ''))
	    WHEN 
            CHARINDEX('DEPT', NODENAME) > 0 AND
            (NODENAME LIKE ('%Branch Brokers%') OR NODENAME LIKE ('%DEPT%'))
            AND	NODENAME NOT LIKE ('%DIVISION%')
            AND NODENAME NOT LIKE ('%MAP%')
        THEN UPPER(REPLACE(NODENAME, 'DEPT', ''))
        ELSE NODENAME
    END AS BRANCHNAME, 
    MGACODE, 
    HIERARCHYCODE, 
    STATUS 
FROM {{ ref ('hierarchy_vc_clean_insurance') }}
WHERE (NODENAME LIKE ('%Branch Brokers%') OR NODENAME LIKE ('%DEPT%'))
AND	NODENAME NOT LIKE ('%DIVISION%')
AND NODENAME NOT LIKE ('%MAP%')
),

HIERARCHYPATHSUBS AS
    (SELECT 
        HIERARCHYLEVEL,
        PARENTNODEID,
        NODEID,
        NODENAME,
        CASE 
            WHEN STARTSWITH(HIERARCHYPATH, '^m3^|^a605^|^a1802^') THEN  REPLACE(HIERARCHYPATH,'^m3^|^a605^|^a1802^','^m4^|^a605^|^a1802^') 
            WHEN STARTSWITH(HIERARCHYPATH, '^m3^|^a605^|^a1801^') THEN  REPLACE(HIERARCHYPATH,'^m3^|^a605^|^a1801^','^m4^|^a605^|^a1801^')
            WHEN STARTSWITH(HIERARCHYPATH, '^m3^|^a605^|^a146^')  THEN  REPLACE(HIERARCHYPATH,'^m3^|^a605^|^a146^', '^m4^|^a605^|^a146^')
            ELSE HIERARCHYPATH 
            END AS HIERARCHYPATH
    FROM {{ ref ('recursive_hierarchy_normalize_insurance') }}
    ),

HIERARCHY AS(
SELECT 
		hps.PARENTNODEID,
		hps.NODEID,
		hps.HIERARCHYPATH,
		hps.HIERARCHYLEVEL,
		(SELECT MIN(b.BRANCHID) FROM H1 b WHERE hps.HIERARCHYPATH LIKE CONCAT('%',b.BRANCHID,'%')) AS BRANCHID,
		LTRIM(RTRIM((SELECT MIN(b.BRANCHNAME) FROM H1 b WHERE hps.HIERARCHYPATH LIKE CONCAT('%',b.BRANCHID,'%')))) AS BRANCHNAME
	FROM HIERARCHYPATHSUBS hps )

SELECT 
b.PARENTNODEID PARENTNODEID_FROM_BROKER, 
b.AGENTCODE, 
b.FIRSTNAME, b.MIDDLENAME, b.LASTNAME, b.FULLAGENTNAME, b.AGENTNAME, b.COMPANYNAME, b.MGACODE, b.AGACODE, b.DATEOFBIRTH, b.PROVINCE, b.COMPANYPROVINCE, b.AGENTSTATUS, b.AGENTTYPE, b.LANGUAGEPREFERENCE, b.SERVICELEVEL, b.CREATEDDATE, b.BROKERID, b.LASTMODIFIEDDATE,
h.PARENTNODEID PARENTNODEID_in_HIERARCHY, h.NODEID, h.HIERARCHYPATH, h.HIERARCHYLEVEL, h.BRANCHID, h.BRANCHNAME,
CASE 
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M1^' THEN 'QC'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M2^' THEN 'West'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M3^' THEN 'Ontario'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M4^' THEN 'Atlantic'
END AS MGA,
CASE 
WHEN BRANCHNAME IN ('MARKHAM', 'RICHMOND') THEN 'TORCE/VANCE' 
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M1^' THEN 'QC'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M2^' THEN 'West'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M3^' THEN 'Ontario'
WHEN SUBSTRING(h.HIERARCHYPATH, 1,4) = '^M4^' THEN 'Atlantic'
END AS REGION
FROM {{ ref ('broker_vc_clean_insurance') }} b LEFT JOIN HIERARCHY h on CONCAT('^', b.PARENTNODEID, '^') = h.NODEID
ORDER BY HIERARCHYLEVEL, NODEID, BRANCHID