{{ config(alias = 'itm_calcs_FH', 
    materialized = 'view',
    database = 'normalize', 
    schema = 'insurance') }} 

WITH TIME_IN_CURRENT_STATUS AS (
    SELECT
        POLICYNUMBER,
        POLICYCODE,
        DBT_VALID_FROM AS END_TIME_IN_STAT,
        LAG(DBT_VALID_FROM) OVER (
            PARTITION BY POLICYCODE
            ORDER BY
                DBT_VALID_FROM
        ) AS START_TIME_IN_STAT,
        CASE
            WHEN
                DATEDIFF('d', START_TIME_IN_STAT, END_TIME_IN_STAT) IS NULL
                THEN 0
            ELSE DATEDIFF('d', START_TIME_IN_STAT, END_TIME_IN_STAT)
        END AS TIME_IN_STAT,
        LAST_VALUE(DBT_VALID_FROM) OVER (
            PARTITION BY POLICYCODE
            ORDER BY
                DBT_VALID_FROM
        ) AS TIME_IN_CURRENT_STAT
    FROM
        {{ ref('status') }}
    WHERE
        POLICYNUMBER is not null and not CONTAINS(POLICYNUMBER, 'CONVERSION')
),

TIME_IN_CURRENT_STATUS_FILTERED AS (
    SELECT
        POLICYNUMBER,
        POLICYCODE,
        TIME_IN_STAT
    FROM
        TIME_IN_CURRENT_STATUS
    WHERE
        END_TIME_IN_STAT = TIME_IN_CURRENT_STAT
),

TERMINATED_END_DATE AS (
    SELECT
        POLICYNUMBER,
        POLICYCODE,
        MIN(DBT_VALID_FROM)::DATE AS START_DATE,
        MAX(DBT_VALID_FROM)::DATE AS END_DATE
    FROM
        {{ ref('status') }}
    WHERE
        POLICYNUMBER is not null and not CONTAINS(POLICYNUMBER, 'CONVERSION')
    GROUP BY
        1, 2
)

SELECT
    FH_POLICYCATEGORY,
    POL.POLICYNUMBER,
    POL.POLICYCODE,
    FH_SERVICINGAGTCODE,
    POL.FH_STATUSCODE,
    FH_STATUSNAMEENG,
    FH_STATUSCATEGORY,
    FH_STARTDATE,
    CREATEDDATE,
    CONTRACTDATE,
    SETTLEMENTDATE,
    EXPIRYDATE,
    RENEWALDATE,
    SENTTOICDATE,
    MAILEDDATE,
    FH_FINPOSTDATE,
    CASE
        WHEN FH_STATUSCATEGORY = 'INFORCE' THEN COALESCE(FH_FINPOSTDATE, SETTLEMENTDATE, MAILEDDATE)    
        WHEN FH_STATUSCATEGORY = 'PENDING' THEN CURRENT_DATE
        WHEN FH_STATUSCATEGORY = 'TERMINATED' and FH_FINPOSTDATE is not null THEN FH_FINPOSTDATE
        WHEN FH_STATUSCATEGORY = 'TERMINATED' and SETTLEMENTDATE is not null THEN SETTLEMENTDATE
        WHEN FH_STATUSCATEGORY = 'TERMINATED' and  ENDDT.END_DATE != '2024-06-28' THEN ENDDT.END_DATE
    END AS ITM_END_DATE,
    CASE
        WHEN ITM_END_DATE is null 
            THEN 99999
        WHEN DATEDIFF('d', FH_STARTDATE, ITM_END_DATE) > -1 THEN DATEDIFF('d', FH_STARTDATE, ITM_END_DATE)
        ELSE 99999
    END AS ITM,
    CASE
        WHEN
            FH_STATUSCATEGORY = 'PENDING'
            AND ( TM.TIME_IN_STAT = 0 OR TM.TIME_IN_STAT IS NULL)
            THEN DATEDIFF('d', FH_STARTDATE, CURRENT_DATE)
        WHEN FH_STATUSCATEGORY = 'PENDING' THEN TM.TIME_IN_STAT
    END AS DAYS_IN_STATUS
FROM
    {{ ref('policy_fh_normalize_insurance') }} AS POL
LEFT JOIN TERMINATED_END_DATE AS ENDDT ON POL.POLICYCODE = ENDDT.POLICYCODE AND POL.POLICYNUMBER = ENDDT.POLICYNUMBER
LEFT JOIN
    TIME_IN_CURRENT_STATUS_FILTERED AS TM
    ON POL.POLICYCODE = TM.POLICYCODE
WHERE
    FH_POLICYCATEGORY != 'SERVICE'
