{{ config(alias = 'itm_calcs_FH', 
    materialized = 'view',
    database = 'normalize', 
    schema = 'insurance') }} 

WITH TIME_IN_CURRENT_STATUS AS (
    SELECT
        POLICYNUMBER,
        POLICYCODE,
        DBT_VALID_FROM::DATE AS DBT_VALID_FROM,
        CASE
            WHEN DBT_VALID_TO::DATE IS NULL THEN CURRENT_DATE
            ELSE DBT_VALID_TO::DATE
        END AS VALID_TO,
        DATEDIFF('d', DBT_VALID_FROM, VALID_TO) AS FH_TIME_IN_STATUS
    FROM
        {{ ref('status') }}
    WHERE
        POLICYNUMBER IS NOT NULL AND NOT CONTAINS(POLICYNUMBER, 'CONVERSION')
    ORDER BY
        DBT_VALID_FROM
),

TIME_IN_CURRENT_STATUS_FILTERED AS (
    SELECT
    DISTINCT POLICYNUMBER,
    POLICYCODE,
    LAST_VALUE(DBT_VALID_FROM) OVER (
        PARTITION BY POLICYCODE
        ORDER BY
            DBT_VALID_FROM
    ) AS VALID_FROM,
    LAST_VALUE(FH_TIME_IN_STATUS) OVER (
        PARTITION BY POLICYCODE
        ORDER BY
            DBT_VALID_FROM
    ) AS TIME_IN_STAT,
FROM
    TIME_IN_CURRENT_STATUS
WHERE
    VALID_TO = CURRENT_DATE
),

TERMINATED_END_DATE AS (
    SELECT
        POLICYNUMBER,
        POLICYCODE,
        MIN(DBT_VALID_FROM)::DATE AS START_DATE,
        MAX(DBT_VALID_FROM)::DATE AS END_DATE
    FROM
        {{ ref('status') }}
    WHERE
        POLICYNUMBER IS NOT NULL AND NOT CONTAINS(POLICYNUMBER, 'CONVERSION')
    GROUP BY
        1, 2
)

SELECT
    FH_POLICYCATEGORY,
    POL.POLICYNUMBER,
    POL.POLICYCODE,
    FH_SERVICINGAGTCODE,
    POL.FH_STATUSCODE,
    FH_STATUSNAMEENG,
    FH_STATUSCATEGORY,
    FH_STARTDATE,
    CREATEDDATE,
    CONTRACTDATE,
    SETTLEMENTDATE,
    EXPIRYDATE,
    RENEWALDATE,
    SENTTOICDATE,
    MAILEDDATE,
    FH_FINPOSTDATE,
    CASE
        WHEN
            FH_STATUSCATEGORY = 'INFORCE'
            THEN COALESCE(FH_FINPOSTDATE, SETTLEMENTDATE, MAILEDDATE)
        WHEN FH_STATUSCATEGORY = 'PENDING' THEN CURRENT_DATE
        WHEN
            FH_STATUSCATEGORY = 'TERMINATED' AND FH_FINPOSTDATE IS NOT NULL
            THEN FH_FINPOSTDATE
        WHEN
            FH_STATUSCATEGORY = 'TERMINATED' AND SETTLEMENTDATE IS NOT NULL
            THEN SETTLEMENTDATE
        WHEN
            FH_STATUSCATEGORY = 'TERMINATED' AND ENDDT.END_DATE != '2024-06-28'
            THEN ENDDT.END_DATE
    END AS ITM_END_DATE,
    CASE
        WHEN ITM_END_DATE IS NULL
            THEN 99999
        WHEN
            DATEDIFF('d', FH_STARTDATE, ITM_END_DATE) > -1
            THEN DATEDIFF('d', FH_STARTDATE, ITM_END_DATE)
        ELSE 99999
    END AS ITM,
    CASE
        WHEN
            FH_STATUSCATEGORY = 'PENDING'
            AND (TM.TIME_IN_STAT = 0 OR TM.TIME_IN_STAT IS NULL)
            THEN DATEDIFF('d', FH_STARTDATE, CURRENT_DATE)
        WHEN FH_STATUSCATEGORY = 'PENDING' THEN TM.TIME_IN_STAT
    END AS DAYS_IN_STATUS
FROM
    {{ ref('policy_fh_normalize_insurance') }} AS POL
LEFT JOIN
    TERMINATED_END_DATE AS ENDDT
    ON
        POL.POLICYCODE = ENDDT.POLICYCODE
        AND POL.POLICYNUMBER = ENDDT.POLICYNUMBER
LEFT JOIN
    TIME_IN_CURRENT_STATUS_FILTERED AS TM
    ON POL.POLICYCODE = TM.POLICYCODE
WHERE
    FH_POLICYCATEGORY != 'SERVICE'
