version: 2

models:
  - name: __POLICYCATEGORY_insurance
    config:
      database: NORMALIZE
    tests:
      - dbt_expectations.expect_column_pair_values_A_to_be_greater_than_B:
          column_A: COMMPREMIUMAMOUNT
          column_B: FYCAMOUNT
          or_equal: FALSE
          row_condition: "policycode is not null and COMMPREMIUMAOUNT > 0" # (Optional)
          config:
            store_values: true
            database: NORMALIZE
            schema: z_TEST_RESULTS
            alias: COMMPREM_GT_FYC__POLICYCATEGORIES
            severity: warn
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - policycode
            - agentcode
          config:
            store_values: true
            database: NORMALIZE
            schema: z_TEST_RESULTS
            alias: POL_AGT_UNIQUE__POLICYCATEGORIES
            severity: warn
    columns:
      - name: fh_policycategory
        description: Holds the Financial Horizons definition of NEW POLICY, NEW RIDER and SERVICE
        tests:
         - not_null:
             config:
              severity: warn
              store_failures: true
              database: NORMALIZE
         - accepted_values:
             values: ['NEW POLICY', 'NEW RIDER', 'SERVICE']
             config:
              severity: warn
              store_failures: true
              database: NORMALIZE
      - name: appcount
        tests: 
          - dbt_utils.accepted_range:
             min_value: 0
             max_value: 1
             config:
              severity: warn
              store_failures: true
              database: NORMALIZE
      - name: splitrate
        tests:
          - dbt_utils.accepted_range:
             min_value: 0
             max_value: 1
             config:
              severity: warn
              store_failures: true
              database: NORMALIZE
      - name: policycode
        tests:
         - relationships:
             field: policycode
             to: ref('policy_vc_clean_insurance')
      - name: policygroupcode
        tests:
          - not_null
      - name: commpremiumamount
        tests:
          - not_null
      - name: fycamount
        tests:
          - not_null
  - name: __POSTDATE_insurance
    config:
      database: NORMALIZE
    tests:
      - dbt_expectations.expect_table_aggregation_to_equal_other_table:
          expression: SUM(FYCAMOUNT)
          compare_model: ref("policy_vc_normalize_insurance")
          compare_expression: SUM(FYCAMOUNT)
          group_by: APPLICATIONDATE
          compare_group_by: APPLICATIONDATE
          row_condition: APPLICATIONDATE >= '2018-01-01'
          compare_row_condition: APPLICATIONDATE >= '2018-01-01' AND PLANTYPE IN ('CI', 'DI', 'Life', 'Permanent', 'Term', 'UL', 'LTC', 'HealthSickness', 'SERVICE', 'Travel', 'WL')
          tolerance_percent: 0.01 
  - name: __FH_FORMAT_insurance
  - name: __COMM_AGT_MAPPED_insurance
  - name: __POLICY_FH

              
             